<a href="https://colab.research.google.com/github/PaulToronto/Howard-University-Coursera-Linear-Algebra-For-Data-Science-Specialization/blob/main/1_2_1_Using_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.2.1 Using Linear Algebra

In [1]:
import numpy as np
import random
import sympy as sp
import matplotlib.pyplot as plt

## 1.2.1.1 Introduction to Linear Algebra Functions in Python

In [2]:
M = np.linspace(-8, 8, 9).reshape(3, 3)
N = np.random.randint(-8, 8, size=(3, 3))
O = 2*N

sp_M = sp.Matrix(M)
sp_N = sp.Matrix(N)
sp_O = sp.Matrix(O)

v1 = np.array([1, 3, 5, 7])
v2 = np.array([2, 4, 6, 8])
v3 = np.array([-2, 5, 1, 3])

sp_v1 = sp.Matrix(v1)
sp_v2 = sp.Matrix(v2)
sp_v3 = sp.Matrix(v3)

### `dot()` for two vectors

The `dot` function calculates the **dot product** of two vectors.

In [3]:
v1, v2

(array([1, 3, 5, 7]), array([2, 4, 6, 8]))

In [4]:
total = 0;
for i in range(4):
    total += v1[i] * v2[i]

total

100

In [5]:
sum([v1[i] * v2[i] for i in range(4)])

100

In [6]:
np.dot(v1, v2)

100

In [7]:
v1.dot(v2)

100

#### Sympy

In [8]:
sp.DotProduct(sp_v1, sp_v2)

DotProduct(Matrix([
[1],
[3],
[5],
[7]]), Matrix([
[2],
[4],
[6],
[8]]))

In [9]:
sp.DotProduct(sp_v1, sp_v2).simplify()

100

In [10]:
sp_v1.dot(sp_v2)

100

### `dot()` for two matrices

This is matrix multiplication

In [11]:
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [12]:
N

array([[-2,  6,  2],
       [-1, -5, -7],
       [ 1, -1,  6]])

In [13]:
np.dot(N, M)

array([[ 12.,  24.,  36.],
       [-10., -36., -62.],
       [ 18.,  30.,  42.]])

In [14]:
N.dot(M)

array([[ 12.,  24.,  36.],
       [-10., -36., -62.],
       [ 18.,  30.,  42.]])

In [15]:
np.matmul(N, M)

array([[ 12.,  24.,  36.],
       [-10., -36., -62.],
       [ 18.,  30.,  42.]])

#### SymPy

In [16]:
sp_N * sp_M

Matrix([
[ 12.0,  24.0,  36.0],
[-10.0, -36.0, -62.0],
[ 18.0,  30.0,  42.0]])

### `linalg.multi_dot()`

In [17]:
np.linalg.multi_dot([M, N, O])

array([[-40., 352., 292.],
       [ 20., 196., 316.],
       [ 80.,  40., 340.]])

In [18]:
M.dot(N).dot(O)

array([[-40., 352., 292.],
       [ 20., 196., 316.],
       [ 80.,  40., 340.]])

#### SymPy

In [19]:
sp_M * sp_N * sp_O

Matrix([
[-40.0, 352.0, 292.0],
[ 20.0, 196.0, 316.0],
[ 80.0,  40.0, 340.0]])

### `vdot()`

In [20]:
np.vdot(v1, v2), np.dot(v1, v2)

(100, 100)

#### SymPy

In [21]:
sp_v1.dot(sp_v2)

100

### `inner()`

Returns the inner product of two arrays

In [22]:
v3, v1

(array([-2,  5,  1,  3]), array([1, 3, 5, 7]))

In [23]:
np.inner(v3, v1)

39

In [24]:
np.dot(v3, v1)

39

#### SymPy

In [25]:
sp_v3.dot(sp_v1)

39

### `matmul()`

In [26]:
np.matmul(M, N)

array([[ 18., -14.,   2.],
       [  6., -14.,   8.],
       [ -6., -14.,  14.]])

In [27]:
np.dot(M, N)

array([[ 18., -14.,   2.],
       [  6., -14.,   8.],
       [ -6., -14.,  14.]])

#### SymPy

In [28]:
sp_M * sp_N

Matrix([
[18.0, -14.0,  2.0],
[ 6.0, -14.0,  8.0],
[-6.0, -14.0, 14.0]])

### `linalg.matrix_power()`

In [29]:
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [30]:
np.linalg.matrix_power(M, 3)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [31]:
M.dot(M).dot(M)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [32]:
np.linalg.multi_dot([M, M, M])

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [33]:
np.matmul(np.matmul(M, M), M)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

#### SymPy

In [34]:
sp_M**3

Matrix([
[-576.0, -432.0, -288.0],
[-144.0,      0,  144.0],
[ 288.0,  432.0,  576.0]])

In [35]:
sp_M * sp_M * sp_M

Matrix([
[-576.0, -432.0, -288.0],
[-144.0,      0,  144.0],
[ 288.0,  432.0,  576.0]])

### `linalg.eig()`

Returns the eigenvalues and eigenvectors of a matrix

In [36]:
O

array([[ -4,  12,   4],
       [ -2, -10, -14],
       [  2,  -2,  12]])

In [37]:
eig_vals, eig_vects = np.linalg.eig(O)

In [38]:
eig_vals

array([12.81776729, -5.18158391, -9.63618337])

In [39]:
eig_vects

array([[ 0.15950282,  0.9909008 , -0.91339123],
       [ 0.50607717, -0.0569129 ,  0.38887712],
       [-0.8476112 , -0.1219694 ,  0.12037875]])

#### SymPy

In [40]:
sp_O.eigenvals()

{-2/3 + 212/(9*(1843/54 + sqrt(151935)*I/18)**(1/3)) + 2*(1843/54 + sqrt(151935)*I/18)**(1/3): 1,
 -2/3 + 212/(9*(-1/2 + sqrt(3)*I/2)*(1843/54 + sqrt(151935)*I/18)**(1/3)) + 2*(-1/2 + sqrt(3)*I/2)*(1843/54 + sqrt(151935)*I/18)**(1/3): 1,
 -2/3 + 2*(-1/2 - sqrt(3)*I/2)*(1843/54 + sqrt(151935)*I/18)**(1/3) + 212/(9*(-1/2 - sqrt(3)*I/2)*(1843/54 + sqrt(151935)*I/18)**(1/3)): 1}

In [41]:
for eig_val in list(sp_O.eigenvals()):
    print(eig_val.evalf())

12.8177672851209 + 0.e-22*I
-9.63618337165891 + 0.e-22*I
-5.18158391346201 - 0.e-22*I


In [42]:
# takes too long to run
# eig_vects = sp_O.eigenvects()

### `linalg.eigh()`

Returns eigenvalues and eigenvectors of a complex Hermition matrix or a real symmetric matrix

In [43]:
eigh_vals, eigh_vects = np.linalg.eigh(N)

In [44]:
eigh_vals

array([-5.3435645 , -1.89103957,  6.23460406])

In [45]:
eigh_vects

array([[ 0.26921815,  0.95401022, -0.13185629],
       [ 0.96114562, -0.25747622,  0.09952432],
       [ 0.06099736, -0.15352685, -0.98626002]])

### `linalg.det()`

Returns the determinant of a matrix

In [46]:
np.linalg.det(M), np.linalg.det(N), np.linalg.det(O)

(0.0, 79.99999999999997, 639.9999999999999)

#### SymPy

In [47]:
sp_M.det(), sp_N.det(), sp_O.det()

(0, 80, 640)

### `linalg.inv()`

Returns the inverse of a matrix

In [48]:
N

array([[-2,  6,  2],
       [-1, -5, -7],
       [ 1, -1,  6]])

In [49]:
np.linalg.inv(N)

array([[-0.4625, -0.475 , -0.4   ],
       [-0.0125, -0.175 , -0.2   ],
       [ 0.075 ,  0.05  ,  0.2   ]])

In [50]:
np.matmul(N, np.linalg.inv(N))

array([[ 1.00000000e+00, -8.32667268e-17,  1.11022302e-16],
       [ 5.55111512e-17,  1.00000000e+00,  5.55111512e-17],
       [ 5.55111512e-17,  8.32667268e-17,  1.00000000e+00]])

In [51]:
N.dot(np.linalg.inv(N))

array([[ 1.00000000e+00, -8.32667268e-17,  1.11022302e-16],
       [ 5.55111512e-17,  1.00000000e+00,  5.55111512e-17],
       [ 5.55111512e-17,  8.32667268e-17,  1.00000000e+00]])

#### SymPy

In [52]:
sp_N**-1

Matrix([
[-37/80, -19/40, -2/5],
[ -1/80,  -7/40, -1/5],
[  3/40,   1/20,  1/5]])

In [53]:
(sp_N**-1).evalf()

Matrix([
[-0.4625, -0.475, -0.4],
[-0.0125, -0.175, -0.2],
[  0.075,   0.05,  0.2]])

In [54]:
sp_N * sp_N**-1

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

## 1.2.1.2 Using Matrices in Python

### Building Matrices Using Numpy

In [55]:
L = np.linspace(0, 120, 25)
L

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100., 105.,
       110., 115., 120.])

In [56]:
M = L.reshape(5, 5)
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [57]:
R = np.random.randint(-5, 4, size=(4, 4))
R

array([[-4,  3,  2, -5],
       [-5, -3, -4, -3],
       [-4,  1,  2, -3],
       [ 3, -5, -4,  1]])

### Building Matrices Using SymPy

In [58]:
sp.Matrix([[1, -1], [3, 4], [0, 2]])

Matrix([
[1, -1],
[3,  4],
[0,  2]])

In [59]:
sp_M = sp.Matrix(M)
sp_M

Matrix([
[  0.0,   5.0,  10.0,  15.0,  20.0],
[ 25.0,  30.0,  35.0,  40.0,  45.0],
[ 50.0,  55.0,  60.0,  65.0,  70.0],
[ 75.0,  80.0,  85.0,  90.0,  95.0],
[100.0, 105.0, 110.0, 115.0, 120.0]])

In [60]:
sp_R = sp.Matrix(R)
sp_R

Matrix([
[-4,  3,  2, -5],
[-5, -3, -4, -3],
[-4,  1,  2, -3],
[ 3, -5, -4,  1]])

### Accessing Matrix Entries: NumPy and SymPy

In [61]:
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [62]:
# first row
M[0]

array([ 0.,  5., 10., 15., 20.])

In [63]:
# first rown
sp_M.row(0)

Matrix([[0.0, 5.0, 10.0, 15.0, 20.0]])

In [64]:
# also first row
sp_M[0, :]

Matrix([[0.0, 5.0, 10.0, 15.0, 20.0]])

In [65]:
# last row
M[-1]

array([100., 105., 110., 115., 120.])

In [66]:
# last row
sp_M.row(-1)

Matrix([[100.0, 105.0, 110.0, 115.0, 120.0]])

In [67]:
#first column
M[:,0]

array([  0.,  25.,  50.,  75., 100.])

In [68]:
sp_M.col(0)

Matrix([
[  0.0],
[ 25.0],
[ 50.0],
[ 75.0],
[100.0]])

In [69]:
# last column
M[:,-1]

array([ 20.,  45.,  70.,  95., 120.])

In [70]:
sp_M.col(-1)

Matrix([
[ 20.0],
[ 45.0],
[ 70.0],
[ 95.0],
[120.0]])

In [71]:
# first 3 rows
M[0:3]

array([[ 0.,  5., 10., 15., 20.],
       [25., 30., 35., 40., 45.],
       [50., 55., 60., 65., 70.]])

In [72]:
# first 3 rows
sp_M[0:3,:]

Matrix([
[ 0.0,  5.0, 10.0, 15.0, 20.0],
[25.0, 30.0, 35.0, 40.0, 45.0],
[50.0, 55.0, 60.0, 65.0, 70.0]])

In [73]:
# third and fourth columns
M[:,2:4]

array([[ 10.,  15.],
       [ 35.,  40.],
       [ 60.,  65.],
       [ 85.,  90.],
       [110., 115.]])

In [74]:
sp_M[:, 2:4]

Matrix([
[ 10.0,  15.0],
[ 35.0,  40.0],
[ 60.0,  65.0],
[ 85.0,  90.0],
[110.0, 115.0]])

In [75]:
# first 3 rows, 2nd, 3rd and 4th columns
M[:3, 1:4]

array([[ 5., 10., 15.],
       [30., 35., 40.],
       [55., 60., 65.]])

In [76]:
sp_M[:3, 1:4]

Matrix([
[ 5.0, 10.0, 15.0],
[30.0, 35.0, 40.0],
[55.0, 60.0, 65.0]])

In [77]:
# first 3 rows, 2nd and 4th columns
M[:3, (1, 3)]

array([[ 5., 15.],
       [30., 40.],
       [55., 65.]])

In [78]:
sp_M[:3, (1, 3)]

Matrix([
[ 5.0, 15.0],
[30.0, 40.0],
[55.0, 65.0]])

In [79]:
# the entry at the intersection of 
# the 2nd row and the 2nd column
M[1, 1]

30.0

In [80]:
sp_M[1,1]

30.0000000000000

## 1.2.1.3 Solving Linear Equations Using Python

### Example

$
\begin{align}
4x + 3y + 2z &= 25 \\
-2x + 2y + 3z &= -10 \\
3x - 5y + 2z &= -4
\end{align}
$

#### Solve Using the Inverse Method

In a nutshell, the solution is found by multiplying the inverse of the coefficent matrix, $M^{-1}$ by the column matrix, $K$.

Let $V$ be the solution, then

$V = M^{-1} * K$

Details about why this equation works are shown in this notebook. 

In [81]:
# M is the coefficient matrix
M = np.array([[4, 3, 2],
              [-2, 2, 3],
              [3, -5, 2]])
M

array([[ 4,  3,  2],
       [-2,  2,  3],
       [ 3, -5,  2]])

In [82]:
# K is the column matrix
K = np.array([[25],
              [-10],
              [-4]])
K

array([[ 25],
       [-10],
       [ -4]])

In [83]:
V = np.array([['x'],
              ['y'],
              ['z']])
V

array([['x'],
       ['y'],
       ['z']], dtype='<U1')

The system of linear equations in this example can be written as:

$
M * V = K \\
\implies 
M^{-1} * M * V = M^{-1} * K \\
\implies
I * V = M^{-1} * K \\
\implies
V = M^{-1} * K
$

In [84]:
np.linalg.inv(M).dot(K)

array([[ 5.],
       [ 3.],
       [-2.]])

##### Sympy

In [85]:
sp_M = sp.Matrix(M)
sp_M

Matrix([
[ 4,  3, 2],
[-2,  2, 3],
[ 3, -5, 2]])

In [86]:
sp_K = sp.Matrix(K)
sp_K

Matrix([
[ 25],
[-10],
[ -4]])

In [87]:
sp_M**-1 * sp_K

Matrix([
[ 5],
[ 3],
[-2]])

##### Symbolic summary of this method

In [88]:
x, y, z = sp.symbols('x y z')
m_11, m_12, m_13 = sp.symbols('m_11 m_12 m_13')
m_21, m_22, m_23 = sp.symbols('m_21 m_22 m_23')
m_31, m_32, m_33 = sp.symbols('m_31 m_32 m_33')
k_1, k_2, k_3 = sp.symbols('k_1 k_2 k_3')

In [89]:
V = sp.Matrix([[x], [y], [z]])
V

Matrix([
[x],
[y],
[z]])

In [90]:
M = sp.Matrix([[m_11, m_12, m_13],
               [m_21, m_22, m_23],
               [m_31, m_32, m_33]])
M

Matrix([
[m_11, m_12, m_13],
[m_21, m_22, m_23],
[m_31, m_32, m_33]])

In [91]:
K = sp.Matrix([[k_1], [k_2], [k_3]])
K

Matrix([
[k_1],
[k_2],
[k_3]])

In [92]:
sp.Eq(M * V, K)

Eq(Matrix([
[m_11*x + m_12*y + m_13*z],
[m_21*x + m_22*y + m_23*z],
[m_31*x + m_32*y + m_33*z]]), Matrix([
[k_1],
[k_2],
[k_3]]))

In [93]:
sp.Eq(V, M**-1 * K)

Eq(Matrix([
[x],
[y],
[z]]), Matrix([
[ k_1*(m_22*m_33 - m_23*m_32)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_2*(-m_12*m_33 + m_13*m_32)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_3*(m_12*m_23 - m_13*m_22)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31)],
[k_1*(-m_21*m_33 + m_23*m_31)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_2*(m_11*m_33 - m_13*m_31)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_3*(-m_11*m_23 + m_13*m_21)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31)],
[ k_1*(m_21*m_32 - m_22*m_31)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_2*(-m_11*m_32 + m_12*m_31)/(

#### Solve Using Reduced Row Echelon Form (SymPy solution only)

In [94]:
# the augmented matrix
A = sp.Matrix([[4, 3, 2, 25],
               [-2, 2, 3, -10],
               [3, -5, 2, -4]])
A

Matrix([
[ 4,  3, 2,  25],
[-2,  2, 3, -10],
[ 3, -5, 2,  -4]])

In [95]:
A.rref(pivots=False)

Matrix([
[1, 0, 0,  5],
[0, 1, 0,  3],
[0, 0, 1, -2]])

#### Solve Using `sympy.linsolve()` (3 methods)

##### Method 1 - List of Equations Form

In [96]:
# note the change in sign of the values from 
# the column matrix
system = [4 * x + 3 * y + 2 * z - 25,
          -2 * x + 2 * y + 3 * z + 10,
          3 * x - 5 * y + 2 * z + 4]
system

[4*x + 3*y + 2*z - 25, -2*x + 2*y + 3*z + 10, 3*x - 5*y + 2*z + 4]

In [97]:
sp.linsolve(system, (x, y, z))

FiniteSet((5, 3, -2))

##### Method 2 - Augmented Matrix Form

In [98]:
A

Matrix([
[ 4,  3, 2,  25],
[-2,  2, 3, -10],
[ 3, -5, 2,  -4]])

In [99]:
sp.linsolve(A, (x, y, z))

FiniteSet((5, 3, -2))

##### Method 3 - $A*x=b$ Form

In [100]:
A = sp_M
A

Matrix([
[ 4,  3, 2],
[-2,  2, 3],
[ 3, -5, 2]])

In [101]:
b = sp_K
b

Matrix([
[ 25],
[-10],
[ -4]])

In [102]:
sp.linsolve((A, b), x, y, z)

FiniteSet((5, 3, -2))

#### Solve Using `np.linalg.solve()`

In [103]:
M = np.array([[4, 3, 2],
              [-2, 2, 3],
              [3, -5, 2]])
M

array([[ 4,  3,  2],
       [-2,  2,  3],
       [ 3, -5,  2]])

In [104]:
K = np.array([[25],
              [-10],
              [-4]])
K

array([[ 25],
       [-10],
       [ -4]])

In [105]:
np.linalg.solve(M, K)

array([[ 5.],
       [ 3.],
       [-2.]])

## 1.2.1.4 Supplemental Reading - [Linear Algebra](https://patrickwalls.github.io/mathematicalpython/linear-algebra/linear-algebra-scipy/)

### Linear Algebra with SciPy

In [106]:
import scipy.linalg as la

#### Numpy Arrays: 1D, 2D and 3D

##### 1D

In [107]:
a = np.array([1, 3, -2, 1])
a

array([ 1,  3, -2,  1])

In [108]:
a.ndim, a.shape, a.size

(1, (4,), 4)

##### 2D

In [109]:
M = np.array([[1, 2],
              [3, 7],
              [-1, 5]])
M

array([[ 1,  2],
       [ 3,  7],
       [-1,  5]])

In [110]:
M.ndim, M.shape, M.size

(2, (3, 2), 6)

In [111]:
M_column = M[:, 1]
print(M_column)

[2 7 5]


In [112]:
M_column.ndim, M_column.shape, M_column.size

(1, (3,), 3)

In [113]:
M_column = M_column.reshape(3, 1)

In [114]:
M_column

array([[2],
       [7],
       [5]])

In [115]:
M_column.ndim, M_column.shape, M_column.size

(2, (3, 1), 3)

##### 3D

In [116]:
M = np.array([[[1, 2, 100], 
               [3, 4, 100]],
              
              [[5, 6, 100], 
               [7, 8, 100]],
              
              [[9, 10, 100], 
               [11, 12, 100]],
              
              [[13, 14, 100],
               [15, 16, 100]]])
M

array([[[  1,   2, 100],
        [  3,   4, 100]],

       [[  5,   6, 100],
        [  7,   8, 100]],

       [[  9,  10, 100],
        [ 11,  12, 100]],

       [[ 13,  14, 100],
        [ 15,  16, 100]]])

In [117]:
M.ndim, M.shape, M.size

(3, (4, 2, 3), 24)

#### Matrix Operations and Functions

##### Arithmetic Operations

Arithmetic array operators: `+`, `-`, `/`, `*`, and `**` are performed elementwise on NumPy arrays

In [118]:
M = np.array([[3, 4],
              [-1, 5]])
M

array([[ 3,  4],
       [-1,  5]])

In [119]:
M + M

array([[ 6,  8],
       [-2, 10]])

In [120]:
M * M

array([[ 9, 16],
       [ 1, 25]])

In [121]:
M / M

array([[1., 1.],
       [1., 1.]])

In [122]:
M**3

array([[ 27,  64],
       [ -1, 125]])

##### Matrix Multiplication

In [123]:
M @ M

array([[ 5, 32],
       [-8, 21]])

In [124]:
M.dot(M)

array([[ 5, 32],
       [-8, 21]])

###### Example

Compute $2I + 3A - AB$ for

$A = \left[\begin{matrix}1 & 3\\-1 & 7\end{matrix}\right]$

$B = \left[\begin{matrix}5 & 2\\1 & 2\end{matrix}\right]$

In [125]:
A = np.array([[1, 3],
              [-1, 7]])
B = np.array([[5, 2],
              [1, 2]])
I = np.eye(2)

In [126]:
2 * I + 3 * A - A @ B

array([[-3.,  1.],
       [-5., 11.]])

##### Matrix Powers - `np.linalg.matrix_power()`

In [127]:
M

array([[ 3,  4],
       [-1,  5]])

In [128]:
np.linalg.matrix_power(M, 3)

array([[-17, 180],
       [-45,  73]])

In [129]:
M @ M @ M

array([[-17, 180],
       [-45,  73]])

In [130]:
M.dot(M).dot(M)

array([[-17, 180],
       [-45,  73]])

##### Transpose

In [131]:
M

array([[ 3,  4],
       [-1,  5]])

In [132]:
M.T

array([[ 3, -1],
       [ 4,  5]])

Notice that $MM^{T}$ is a symmetric matrix

In [133]:
M @ M.T

array([[25, 17],
       [17, 26]])

In [134]:
M.T @ M

array([[10,  7],
       [ 7, 41]])

##### Inverse

In [135]:
A = np.array([[1, 2],
              [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [136]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

##### Trace

In [137]:
np.trace(A)

5

##### Determinant

In [138]:
# scipy
la.det(A)

-2.0

In [139]:
# numpy 
np.linalg.det(A)

-2.0000000000000004

In [140]:
sp_A = sp.Matrix(A)
sp_A

Matrix([
[1, 2],
[3, 4]])

In [141]:
sp_A.det(), sp.det(sp_A)

(-2, -2)

### Solving Linear Systems

#### Linear Systems

A **linear system of equations** is a collection of linear equations:

$
a_{00}x_{0} + a_{01}x_{1} + \dots + a_{0n}x_{n} = b_{0} \\
a_{10}x_{0} + a_{11}x_{1} + \dots + a_{1n}x_{n} = b_{1} \\
\vdots \\
a_{m0}x_{0} + a_{m1}x_{1} + \dots + a_{mn}x_{n} = b_{m}
$

In matrix notation, a linear system is $Ax = b$ where

$A = 
\left[
\begin{matrix}
a_{00} & a_{01} & \dots & a_{0n} \\
a_{10} & a_{11} & \dots & a \\
\vdots & & & \vdots \\
a_{m0} & a_{m1} & \dots & a_{mn}
\end{matrix}
\right] ,
x = 
\left[
\begin{matrix}
x_{0}  \\
x_{1}  \\
\vdots  \\
x_{n}  
\end{matrix}
\right] ,
b = 
\left[
\begin{matrix}
b_{0}  \\
b_{1}  \\
\vdots  \\
b_{m}  
\end{matrix}
\right]
$

#### Gaussian Elimination

Perform elementary row operations to reduce the system to its row echelen form and then solve

###### Elmentary Row Operations

1. Add $k$ times row $j$ to row $i$
2. Multiply row $i$ by scalar $k$
3. Switch rows $i$ and $j$