<a href="https://colab.research.google.com/github/PaulToronto/Howard-University-Coursera-Linear_Algebra-For-Data-Science-Specialization/blob/main/1_2_1_Using_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.2.1 Using Linear Algebra

In [1]:
import numpy as np
import random
import sympy as sp

## 1.2.1.1 Introduction to Linear Algebra Functions in Python

In [2]:
M = np.linspace(-8, 8, 9).reshape(3, 3)
N = np.random.randint(-8, 8, size=(3, 3))
O = 2*N

sp_M = sp.Matrix(M)
sp_N = sp.Matrix(N)
sp_O = sp.Matrix(O)

v1 = np.array([1, 3, 5, 7])
v2 = np.array([2, 4, 6, 8])
v3 = np.array([-2, 5, 1, 3])

sp_v1 = sp.Matrix(v1)
sp_v2 = sp.Matrix(v2)
sp_v3 = sp.Matrix(v3)

### `dot()` for two vectors

The `dot` function calculates the **dot product* of two vectors.

In [3]:
v1, v2

(array([1, 3, 5, 7]), array([2, 4, 6, 8]))

In [4]:
np.dot(v1, v2)

100

In [5]:
v1.dot(v2)

100

#### Sympy

In [6]:
sp.DotProduct(sp_v1, sp_v2)

DotProduct(Matrix([
[1],
[3],
[5],
[7]]), Matrix([
[2],
[4],
[6],
[8]]))

In [7]:
sp.DotProduct(sp_v1, sp_v2).simplify()

100

In [8]:
sp_v1.dot(sp_v2)

100

### `dot()` for two matrices

This is matrix multiplication

In [9]:
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [10]:
N

array([[ 3, -4,  5],
       [ 5,  3, -1],
       [-4,  4, -1]])

In [11]:
np.dot(N, M)

array([[  4.,  12.,  20.],
       [-50., -36., -22.],
       [ 20.,  18.,  16.]])

In [12]:
N.dot(M)

array([[  4.,  12.,  20.],
       [-50., -36., -22.],
       [ 20.,  18.,  16.]])

In [13]:
np.matmul(N, M)

array([[  4.,  12.,  20.],
       [-50., -36., -22.],
       [ 20.,  18.,  16.]])

#### SymPy

In [14]:
sp_N * sp_M

Matrix([
[  4.0,  12.0,  20.0],
[-50.0, -36.0, -22.0],
[ 20.0,  18.0,  16.0]])

### `linalg.multi_dot()`

In [15]:
np.linalg.multi_dot([M, N, O])

array([[  -8.,   52., -316.],
       [ 172.,  112., -148.],
       [ 352.,  172.,   20.]])

#### SymPy

In [16]:
sp_M * sp_N * sp_O

Matrix([
[ -8.0,  52.0, -316.0],
[172.0, 112.0, -148.0],
[352.0, 172.0,   20.0]])

### `vdot()`

In [17]:
np.vdot(v1, v2)

100

#### SymPy

In [18]:
sp_v1.dot(sp_v2)

100

### `inner()`

Returns the inner product of two arrays

In [19]:
v3, v1

(array([-2,  5,  1,  3]), array([1, 3, 5, 7]))

In [20]:
np.inner(v3, v1)

39

In [21]:
np.dot(v3, v1)

39

#### SymPy

In [22]:
sp_v3.dot(sp_v1)

39

### `matmul()`

In [23]:
np.matmul(M, N)

array([[-38.,  -2., -30.],
       [-14.,  16., -12.],
       [ 10.,  34.,   6.]])

In [24]:
np.dot(M, N)

array([[-38.,  -2., -30.],
       [-14.,  16., -12.],
       [ 10.,  34.,   6.]])

#### SymPy

In [25]:
sp_M * sp_N

Matrix([
[-38.0, -2.0, -30.0],
[-14.0, 16.0, -12.0],
[ 10.0, 34.0,   6.0]])

### `linalg.matrix_power()`

In [26]:
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [27]:
np.linalg.matrix_power(M, 3)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [28]:
M.dot(M).dot(M)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [29]:
np.linalg.multi_dot([M, M, M])

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [30]:
np.matmul(np.matmul(M, M), M)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

#### SymPy

In [31]:
sp_M**3

Matrix([
[-576.0, -432.0, -288.0],
[-144.0,      0,  144.0],
[ 288.0,  432.0,  576.0]])

In [32]:
sp_M * sp_M * sp_M

Matrix([
[-576.0, -432.0, -288.0],
[-144.0,      0,  144.0],
[ 288.0,  432.0,  576.0]])

### `linalg.eig()`

Returns the eigenvalues and eigenvectors of a matrix

In [33]:
eig_vals, eig_vects = np.linalg.eig(O)

In [34]:
eig_vals

array([1.90984644+12.67854927j, 1.90984644-12.67854927j,
       6.18030712 +0.j        ])

In [35]:
eig_vects

array([[ 0.61670754+0.j        ,  0.61670754-0.j        ,
         0.13797034+0.j        ],
       [-0.21827246-0.48333836j, -0.21827246+0.48333836j,
         0.77218586+0.j        ],
       [-0.42686082+0.39522501j, -0.42686082-0.39522501j,
         0.62023639+0.j        ]])

#### SymPy

In [36]:
sp_O.eigenvals()

{-232/(9*(782/27 + 2*sqrt(745))**(1/3)) + 10/3 + 2*(782/27 + 2*sqrt(745))**(1/3): 1,
 10/3 - 232/(9*(-1/2 + sqrt(3)*I/2)*(782/27 + 2*sqrt(745))**(1/3)) + 2*(-1/2 + sqrt(3)*I/2)*(782/27 + 2*sqrt(745))**(1/3): 1,
 10/3 + 2*(-1/2 - sqrt(3)*I/2)*(782/27 + 2*sqrt(745))**(1/3) - 232/(9*(-1/2 - sqrt(3)*I/2)*(782/27 + 2*sqrt(745))**(1/3)): 1}

In [37]:
for eig_val in list(sp_O.eigenvals()):
    print(eig_val.evalf())

6.18030711841767
1.90984644079116 + 12.6785492650533*I
1.90984644079116 - 12.6785492650533*I


In [38]:
# takes too long to run
# eig_vects = sp_O.eigenvects()

### `linalg.eigh()`

Returns eigenvalues and eigenvectors of a complex Hermition matix or a real symmetric matrix

In [39]:
eigh_vals, eigh_vects = np.linalg.eigh(N)

In [40]:
eigh_vals

array([-7.17890835,  4.17890835,  8.        ])

In [41]:
eigh_vects

array([[-5.21546999e-01, -4.77481651e-01, -7.07106781e-01],
       [ 5.21546999e-01,  4.77481651e-01, -7.07106781e-01],
       [-6.75261027e-01,  7.37578840e-01, -1.66533454e-16]])

### `linalg.det()`

Returns the determinant of a matrix

In [42]:
np.linalg.det(M), np.linalg.det(N), np.linalg.det(O)

(0.0, 126.99999999999999, 1016.0000000000002)

#### SymPy

In [43]:
sp_M.det(), sp_N.det(), sp_O.det()

(0, 127, 1016)

### `linalg.inv()`

Returns the inverse of a matrix

In [44]:
N

array([[ 3, -4,  5],
       [ 5,  3, -1],
       [-4,  4, -1]])

In [45]:
np.linalg.inv(N)

array([[ 0.00787402,  0.12598425, -0.08661417],
       [ 0.07086614,  0.13385827,  0.22047244],
       [ 0.2519685 ,  0.03149606,  0.22834646]])

In [46]:
np.matmul(N, np.linalg.inv(N))

array([[ 1.00000000e+00, -1.31838984e-16,  2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00,  5.55111512e-17],
       [ 0.00000000e+00,  1.59594560e-16,  1.00000000e+00]])

In [47]:
N.dot(np.linalg.inv(N))

array([[ 1.00000000e+00, -1.31838984e-16,  2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00,  5.55111512e-17],
       [ 0.00000000e+00,  1.59594560e-16,  1.00000000e+00]])

#### SymPy

In [48]:
sp_N**-1

Matrix([
[ 1/127, 16/127, -11/127],
[ 9/127, 17/127,  28/127],
[32/127,  4/127,  29/127]])

In [49]:
(sp_N**-1).evalf()

Matrix([
[0.0078740157480315, 0.125984251968504, -0.0866141732283465],
[0.0708661417322835, 0.133858267716535,   0.220472440944882],
[ 0.251968503937008, 0.031496062992126,   0.228346456692913]])

In [50]:
sp_N * sp_N**-1

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])