<a href="https://colab.research.google.com/github/PaulToronto/Howard-University-Coursera-Linear-Algebra-For-Data-Science-Specialization/blob/main/1_2_1_Using_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.2.1 Using Linear Algebra

In [216]:
import numpy as np
import random
import sympy as sp
import matplotlib.pyplot as plt

## 1.2.1.1 Introduction to Linear Algebra Functions in Python

In [217]:
M = np.linspace(-8, 8, 9).reshape(3, 3)
N = np.random.randint(-8, 8, size=(3, 3))
O = 2*N

sp_M = sp.Matrix(M)
sp_N = sp.Matrix(N)
sp_O = sp.Matrix(O)

v1 = np.array([1, 3, 5, 7])
v2 = np.array([2, 4, 6, 8])
v3 = np.array([-2, 5, 1, 3])

sp_v1 = sp.Matrix(v1)
sp_v2 = sp.Matrix(v2)
sp_v3 = sp.Matrix(v3)

### `dot()` for two vectors

The `dot` function calculates the **dot product** of two vectors.

In [218]:
v1, v2

(array([1, 3, 5, 7]), array([2, 4, 6, 8]))

In [219]:
total = 0;
for i in range(4):
    total += v1[i] * v2[i]

total

100

In [220]:
sum([v1[i] * v2[i] for i in range(4)])

100

In [221]:
np.dot(v1, v2)

100

In [222]:
v1.dot(v2)

100

#### Sympy

In [223]:
sp.DotProduct(sp_v1, sp_v2)

DotProduct(Matrix([
[1],
[3],
[5],
[7]]), Matrix([
[2],
[4],
[6],
[8]]))

In [224]:
sp.DotProduct(sp_v1, sp_v2).simplify()

100

In [225]:
sp_v1.dot(sp_v2)

100

### `dot()` for two matrices

This is matrix multiplication

In [226]:
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [227]:
N

array([[ 6, -5, -1],
       [ 5,  3,  0],
       [ 0, -3,  7]])

In [228]:
np.dot(N, M)

array([[-42., -42., -42.],
       [-46., -30., -14.],
       [ 34.,  42.,  50.]])

In [229]:
N.dot(M)

array([[-42., -42., -42.],
       [-46., -30., -14.],
       [ 34.,  42.,  50.]])

In [230]:
np.matmul(N, M)

array([[-42., -42., -42.],
       [-46., -30., -14.],
       [ 34.,  42.,  50.]])

#### SymPy

In [231]:
sp_N * sp_M

Matrix([
[-42.0, -42.0, -42.0],
[-46.0, -30.0, -14.0],
[ 34.0,  42.0,  50.0]])

### `linalg.multi_dot()`

In [232]:
np.linalg.multi_dot([M, N, O])

array([[ -596.,  1104.,  -124.],
       [ -104.,    48.,   248.],
       [  388., -1008.,   620.]])

In [233]:
M.dot(N).dot(O)

array([[ -596.,  1104.,  -124.],
       [ -104.,    48.,   248.],
       [  388., -1008.,   620.]])

#### SymPy

In [234]:
sp_M * sp_N * sp_O

Matrix([
[-596.0,  1104.0, -124.0],
[-104.0,    48.0,  248.0],
[ 388.0, -1008.0,  620.0]])

### `vdot()`

In [235]:
np.vdot(v1, v2), np.dot(v1, v2)

(100, 100)

#### SymPy

In [236]:
sp_v1.dot(sp_v2)

100

### `inner()`

Returns the inner product of two arrays

In [237]:
v3, v1

(array([-2,  5,  1,  3]), array([1, 3, 5, 7]))

In [238]:
np.inner(v3, v1)

39

In [239]:
np.dot(v3, v1)

39

#### SymPy

In [240]:
sp_v3.dot(sp_v1)

39

### `matmul()`

In [241]:
np.matmul(M, N)

array([[-78.,  34., -20.],
       [-12.,   4.,  16.],
       [ 54., -26.,  52.]])

In [242]:
np.dot(M, N)

array([[-78.,  34., -20.],
       [-12.,   4.,  16.],
       [ 54., -26.,  52.]])

#### SymPy

In [243]:
sp_M * sp_N

Matrix([
[-78.0,  34.0, -20.0],
[-12.0,   4.0,  16.0],
[ 54.0, -26.0,  52.0]])

### `linalg.matrix_power()`

In [244]:
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [245]:
np.linalg.matrix_power(M, 3)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [246]:
M.dot(M).dot(M)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [247]:
np.linalg.multi_dot([M, M, M])

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [248]:
np.matmul(np.matmul(M, M), M)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

#### SymPy

In [249]:
sp_M**3

Matrix([
[-576.0, -432.0, -288.0],
[-144.0,      0,  144.0],
[ 288.0,  432.0,  576.0]])

In [250]:
sp_M * sp_M * sp_M

Matrix([
[-576.0, -432.0, -288.0],
[-144.0,      0,  144.0],
[ 288.0,  432.0,  576.0]])

### `linalg.eig()`

Returns the eigenvalues and eigenvectors of a matrix

In [251]:
O

array([[ 12, -10,  -2],
       [ 10,   6,   0],
       [  0,  -6,  14]])

In [252]:
eig_vals, eig_vects = np.linalg.eig(O)

In [253]:
eig_vals

array([ 8.52529911+9.81952299j,  8.52529911-9.81952299j,
       14.94940178+0.j        ])

In [254]:
eig_vects

array([[ 0.66669283+0.j        ,  0.66669283-0.j        ,
        -0.13852103+0.j        ],
       [ 0.16377394-0.6368283j ,  0.16377394+0.6368283j ,
        -0.15478244+0.j        ],
       [ 0.3394094 -0.08916129j,  0.3394094 +0.08916129j,
         0.97818931+0.j        ]])

#### SymPy

In [255]:
sp_O.eigenvals()

{-124/(9*(730/27 + 2*sqrt(21423)/9)**(1/3)) + 2*(730/27 + 2*sqrt(21423)/9)**(1/3) + 32/3: 1,
 32/3 - 124/(9*(-1/2 + sqrt(3)*I/2)*(730/27 + 2*sqrt(21423)/9)**(1/3)) + 2*(-1/2 + sqrt(3)*I/2)*(730/27 + 2*sqrt(21423)/9)**(1/3): 1,
 32/3 + 2*(-1/2 - sqrt(3)*I/2)*(730/27 + 2*sqrt(21423)/9)**(1/3) - 124/(9*(-1/2 - sqrt(3)*I/2)*(730/27 + 2*sqrt(21423)/9)**(1/3)): 1}

In [256]:
for eig_val in list(sp_O.eigenvals()):
    print(eig_val.evalf())

14.9494017784187
8.52529911079064 + 9.81952298712835*I
8.52529911079064 - 9.81952298712835*I


In [257]:
# takes too long to run
# eig_vects = sp_O.eigenvects()

### `linalg.eigh()`

Returns eigenvalues and eigenvectors of a complex Hermition matrix or a real symmetric matrix

In [258]:
eigh_vals, eigh_vects = np.linalg.eigh(N)

In [259]:
eigh_vals

array([-1.43148995,  6.71294498, 10.71854497])

In [260]:
eigh_vects

array([[-0.53538349,  0.55546961, -0.63625312],
       [ 0.79573941,  0.07920385, -0.60043779],
       [ 0.28313124,  0.82775616,  0.4844135 ]])

### `linalg.det()`

Returns the determinant of a matrix

In [261]:
np.linalg.det(M), np.linalg.det(N), np.linalg.det(O)

(0.0, 316.00000000000006, 2527.999999999999)

#### SymPy

In [262]:
sp_M.det(), sp_N.det(), sp_O.det()

(0, 316, 2528)

### `linalg.inv()`

Returns the inverse of a matrix

In [263]:
N

array([[ 6, -5, -1],
       [ 5,  3,  0],
       [ 0, -3,  7]])

In [264]:
np.linalg.inv(N)

array([[ 0.0664557 ,  0.12025316,  0.00949367],
       [-0.11075949,  0.13291139, -0.01582278],
       [-0.04746835,  0.05696203,  0.13607595]])

In [265]:
np.matmul(N, np.linalg.inv(N))

array([[1.00000000e+00, 2.77555756e-17, 0.00000000e+00],
       [1.38777878e-17, 1.00000000e+00, 1.73472348e-17],
       [2.08166817e-17, 2.77555756e-17, 1.00000000e+00]])

In [266]:
N.dot(np.linalg.inv(N))

array([[1.00000000e+00, 2.77555756e-17, 0.00000000e+00],
       [1.38777878e-17, 1.00000000e+00, 1.73472348e-17],
       [2.08166817e-17, 2.77555756e-17, 1.00000000e+00]])

#### SymPy

In [267]:
sp_N**-1

Matrix([
[ 21/316, 19/158,  3/316],
[-35/316, 21/158, -5/316],
[-15/316,  9/158, 43/316]])

In [268]:
(sp_N**-1).evalf()

Matrix([
[ 0.0664556962025316,  0.120253164556962, 0.00949367088607595],
[ -0.110759493670886,  0.132911392405063, -0.0158227848101266],
[-0.0474683544303797, 0.0569620253164557,   0.136075949367089]])

In [269]:
sp_N * sp_N**-1

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

## 1.2.1.2 Using Matrices in Python

### Building Matrices Using Numpy

In [270]:
L = np.linspace(0, 120, 25)
L

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100., 105.,
       110., 115., 120.])

In [271]:
M = L.reshape(5, 5)
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [272]:
R = np.random.randint(-5, 4, size=(4, 4))
R

array([[-2, -4, -2, -2],
       [ 3,  0, -2,  0],
       [-1,  2,  3, -1],
       [-3, -5, -3, -1]])

### Building Matrices Using SymPy

In [273]:
sp.Matrix([[1, -1], [3, 4], [0, 2]])

Matrix([
[1, -1],
[3,  4],
[0,  2]])

In [274]:
sp_M = sp.Matrix(M)
sp_M

Matrix([
[  0.0,   5.0,  10.0,  15.0,  20.0],
[ 25.0,  30.0,  35.0,  40.0,  45.0],
[ 50.0,  55.0,  60.0,  65.0,  70.0],
[ 75.0,  80.0,  85.0,  90.0,  95.0],
[100.0, 105.0, 110.0, 115.0, 120.0]])

In [275]:
sp_R = sp.Matrix(R)
sp_R

Matrix([
[-2, -4, -2, -2],
[ 3,  0, -2,  0],
[-1,  2,  3, -1],
[-3, -5, -3, -1]])

### Accessing Matrix Entries: NumPy and SymPy

In [276]:
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [277]:
# first row
M[0]

array([ 0.,  5., 10., 15., 20.])

In [278]:
# first rown
sp_M.row(0)

Matrix([[0.0, 5.0, 10.0, 15.0, 20.0]])

In [279]:
# also first row
sp_M[0, :]

Matrix([[0.0, 5.0, 10.0, 15.0, 20.0]])

In [280]:
# last row
M[-1]

array([100., 105., 110., 115., 120.])

In [281]:
# last row
sp_M.row(-1)

Matrix([[100.0, 105.0, 110.0, 115.0, 120.0]])

In [282]:
#first column
M[:,0]

array([  0.,  25.,  50.,  75., 100.])

In [283]:
sp_M.col(0)

Matrix([
[  0.0],
[ 25.0],
[ 50.0],
[ 75.0],
[100.0]])

In [284]:
# last column
M[:,-1]

array([ 20.,  45.,  70.,  95., 120.])

In [285]:
sp_M.col(-1)

Matrix([
[ 20.0],
[ 45.0],
[ 70.0],
[ 95.0],
[120.0]])

In [286]:
# first 3 rows
M[0:3]

array([[ 0.,  5., 10., 15., 20.],
       [25., 30., 35., 40., 45.],
       [50., 55., 60., 65., 70.]])

In [287]:
# first 3 rows
sp_M[0:3,:]

Matrix([
[ 0.0,  5.0, 10.0, 15.0, 20.0],
[25.0, 30.0, 35.0, 40.0, 45.0],
[50.0, 55.0, 60.0, 65.0, 70.0]])

In [288]:
# third and fourth columns
M[:,2:4]

array([[ 10.,  15.],
       [ 35.,  40.],
       [ 60.,  65.],
       [ 85.,  90.],
       [110., 115.]])

In [289]:
sp_M[:, 2:4]

Matrix([
[ 10.0,  15.0],
[ 35.0,  40.0],
[ 60.0,  65.0],
[ 85.0,  90.0],
[110.0, 115.0]])

In [290]:
# first 3 rows, 2nd, 3rd and 4th columns
M[:3, 1:4]

array([[ 5., 10., 15.],
       [30., 35., 40.],
       [55., 60., 65.]])

In [291]:
sp_M[:3, 1:4]

Matrix([
[ 5.0, 10.0, 15.0],
[30.0, 35.0, 40.0],
[55.0, 60.0, 65.0]])

In [292]:
# first 3 rows, 2nd and 4th columns
M[:3, (1, 3)]

array([[ 5., 15.],
       [30., 40.],
       [55., 65.]])

In [293]:
sp_M[:3, (1, 3)]

Matrix([
[ 5.0, 15.0],
[30.0, 40.0],
[55.0, 65.0]])

In [294]:
# the entry at the intersection of 
# the 2nd row and the 2nd column
M[1, 1]

30.0

In [295]:
sp_M[1,1]

30.0000000000000

## 1.2.1.3 Solving Linear Equations Using Python

### Example

$
\begin{align}
4x + 3y + 2x &= 25 \\
-2x + 2y + 3z &= -10 \\
3x - 5y + 2z &= -4
\end{align}
$

#### Solve Using the Inverse Method

In a nutshell, the solution is found by multiplying the inverse of the coefficent matrix, $M^{-1}$ by the column matrix, $K$.

Let $V$ be the solution, then

$V = M^{-1} * K$

Details about why this equation works are shown in this notebook. 

In [296]:
# M is the coefficient matrix
M = np.array([[4, 3, 2],
              [-2, 2, 3],
              [3, -5, 2]])
M

array([[ 4,  3,  2],
       [-2,  2,  3],
       [ 3, -5,  2]])

In [297]:
# K is the column matrix
K = np.array([[25],
              [-10],
              [-4]])
K

array([[ 25],
       [-10],
       [ -4]])

In [298]:
V = np.array([['x'],
              ['y'],
              ['z']])
V

array([['x'],
       ['y'],
       ['z']], dtype='<U1')

The system of linear equations in this example can be written as:

$
M * V = K \\
\implies 
M^{-1} * M * V = M^{-1} * K \\
\implies
I * V = M^{-1} * K \\
\implies
V = M^{-1} * K
$

In [299]:
np.linalg.inv(M).dot(K)

array([[ 5.],
       [ 3.],
       [-2.]])

##### Sympy

In [300]:
sp_M = sp.Matrix(M)
sp_M

Matrix([
[ 4,  3, 2],
[-2,  2, 3],
[ 3, -5, 2]])

In [301]:
sp_K = sp.Matrix(K)
sp_K

Matrix([
[ 25],
[-10],
[ -4]])

In [302]:
sp_M**-1 * sp_K

Matrix([
[ 5],
[ 3],
[-2]])

##### Symbolic summary of this method

In [303]:
x, y, z = sp.symbols('x y z')
m_11, m_12, m_13 = sp.symbols('m_11 m_12 m_13')
m_21, m_22, m_23 = sp.symbols('m_21 m_22 m_23')
m_31, m_32, m_33 = sp.symbols('m_31 m_32 m_33')
k_1, k_2, k_3 = sp.symbols('k_1 k_2 k_3')

In [304]:
V = sp.Matrix([[x], [y], [z]])
V

Matrix([
[x],
[y],
[z]])

In [305]:
M = sp.Matrix([[m_11, m_12, m_13],
               [m_21, m_22, m_23],
               [m_31, m_32, m_33]])
M

Matrix([
[m_11, m_12, m_13],
[m_21, m_22, m_23],
[m_31, m_32, m_33]])

In [306]:
K = sp.Matrix([[k_1], [k_2], [k_3]])
K

Matrix([
[k_1],
[k_2],
[k_3]])

In [307]:
sp.Eq(M * V, K)

Eq(Matrix([
[m_11*x + m_12*y + m_13*z],
[m_21*x + m_22*y + m_23*z],
[m_31*x + m_32*y + m_33*z]]), Matrix([
[k_1],
[k_2],
[k_3]]))

In [308]:
sp.Eq(V, M**-1 * K)

Eq(Matrix([
[x],
[y],
[z]]), Matrix([
[ k_1*(m_22*m_33 - m_23*m_32)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_2*(-m_12*m_33 + m_13*m_32)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_3*(m_12*m_23 - m_13*m_22)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31)],
[k_1*(-m_21*m_33 + m_23*m_31)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_2*(m_11*m_33 - m_13*m_31)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_3*(-m_11*m_23 + m_13*m_21)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31)],
[ k_1*(m_21*m_32 - m_22*m_31)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_2*(-m_11*m_32 + m_12*m_31)/(

#### Solve Using Reduced Row Echelon Form (SymPy solution only)

In [309]:
# the augmented matrix
A = sp.Matrix([[4, 3, 2, 25],
               [-2, 2, 3, -10],
               [3, -5, 2, -4]])
A

Matrix([
[ 4,  3, 2,  25],
[-2,  2, 3, -10],
[ 3, -5, 2,  -4]])

In [310]:
A.rref(pivots=False)

Matrix([
[1, 0, 0,  5],
[0, 1, 0,  3],
[0, 0, 1, -2]])

#### Solve Using `sympy.linsolve()` (3 methods)

##### Method 1 - List of Equations Form

In [311]:
# note the change in sign of the values from 
# the column matrix
system = [4 * x + 3 * y + 2 * z - 25,
          -2 * x + 2 * y + 3 * z + 10,
          3 * x - 5 * y + 2 * z + 4]
system

[4*x + 3*y + 2*z - 25, -2*x + 2*y + 3*z + 10, 3*x - 5*y + 2*z + 4]

In [312]:
sp.linsolve(system, (x, y, z))

FiniteSet((5, 3, -2))

##### Method 2 - Augmented Matrix Form

In [313]:
A

Matrix([
[ 4,  3, 2,  25],
[-2,  2, 3, -10],
[ 3, -5, 2,  -4]])

In [314]:
sp.linsolve(A, (x, y, z))

FiniteSet((5, 3, -2))

##### Method 3 - $A*x=b$ Form

In [315]:
A = sp_M
A

Matrix([
[ 4,  3, 2],
[-2,  2, 3],
[ 3, -5, 2]])

In [316]:
b = sp_K
b

Matrix([
[ 25],
[-10],
[ -4]])

In [317]:
sp.linsolve((A, b), x, y, z)

FiniteSet((5, 3, -2))

#### Solve Using `np.linalg.solve()`

In [318]:
M = np.array([[4, 3, 2],
              [-2, 2, 3],
              [3, -5, 2]])
M

array([[ 4,  3,  2],
       [-2,  2,  3],
       [ 3, -5,  2]])

In [319]:
K = np.array([[25],
              [-10],
              [-4]])
K

array([[ 25],
       [-10],
       [ -4]])

In [320]:
np.linalg.solve(M, K)

array([[ 5.],
       [ 3.],
       [-2.]])

## 1.2.1.4 Supplemental Reading - [Linear Algebra](https://patrickwalls.github.io/mathematicalpython/linear-algebra/linear-algebra-scipy/)

### Linear Algebra with SciPy

In [321]:
import scipy.linalg as la

#### Numpy Arrays: 1D, 2D and 3D

##### 1D

In [322]:
a = np.array([1, 3, -2, 1])
a

array([ 1,  3, -2,  1])

In [323]:
a.ndim, a.shape, a.size

(1, (4,), 4)

##### 2D

In [324]:
M = np.array([[1, 2],
              [3, 7],
              [-1, 5]])
M

array([[ 1,  2],
       [ 3,  7],
       [-1,  5]])

In [325]:
M.ndim, M.shape, M.size

(2, (3, 2), 6)

In [326]:
M_column = M[:, 1]
print(M_column)

[2 7 5]


In [327]:
M_column.ndim, M_column.shape, M_column.size

(1, (3,), 3)

In [328]:
M_column = M_column.reshape(3, 1)

In [329]:
M_column

array([[2],
       [7],
       [5]])

In [330]:
M_column.ndim, M_column.shape, M_column.size

(2, (3, 1), 3)

##### 3D

In [331]:
M = np.array([[[1, 2, 100], 
               [3, 4, 100]],
              
              [[5, 6, 100], 
               [7, 8, 100]],
              
              [[9, 10, 100], 
               [11, 12, 100]],
              
              [[13, 14, 100],
               [15, 16, 100]]])
M

array([[[  1,   2, 100],
        [  3,   4, 100]],

       [[  5,   6, 100],
        [  7,   8, 100]],

       [[  9,  10, 100],
        [ 11,  12, 100]],

       [[ 13,  14, 100],
        [ 15,  16, 100]]])

In [332]:
M.ndim, M.shape, M.size

(3, (4, 2, 3), 24)

#### Matrix Operations and Functions

##### Arithmetic Operations

Arithmetic array operators: `+`, `-`, `/`, `*`, and `**` are performed elementwise on NumPy arrays

In [333]:
M = np.array([[3, 4],
              [-1, 5]])
M

array([[ 3,  4],
       [-1,  5]])

In [334]:
M + M

array([[ 6,  8],
       [-2, 10]])

In [335]:
M * M

array([[ 9, 16],
       [ 1, 25]])

In [336]:
M / M

array([[1., 1.],
       [1., 1.]])

In [337]:
M**3

array([[ 27,  64],
       [ -1, 125]])

##### Matrix Multiplication

In [338]:
M @ M

array([[ 5, 32],
       [-8, 21]])

In [339]:
M.dot(M)

array([[ 5, 32],
       [-8, 21]])

###### Example

Compute $2I + 3A - AB$ for

$A = \left[\begin{matrix}1 & 3\\-1 & 7\end{matrix}\right]$

$B = \left[\begin{matrix}5 & 2\\1 & 2\end{matrix}\right]$

In [340]:
A = np.array([[1, 3],
              [-1, 7]])
B = np.array([[5, 2],
              [1, 2]])
I = np.eye(2)

In [341]:
2 * I + 3 * A - A @ B

array([[-3.,  1.],
       [-5., 11.]])

##### Matrix Powers - `np.linalg.matrix_power()`

In [342]:
M

array([[ 3,  4],
       [-1,  5]])

In [343]:
np.linalg.matrix_power(M, 3)

array([[-17, 180],
       [-45,  73]])

In [344]:
M @ M @ M

array([[-17, 180],
       [-45,  73]])

In [345]:
M.dot(M).dot(M)

array([[-17, 180],
       [-45,  73]])

##### Transpose

In [346]:
M

array([[ 3,  4],
       [-1,  5]])

In [347]:
M.T

array([[ 3, -1],
       [ 4,  5]])

Notice that $MM^{T}$ is a symmetric matrix

In [348]:
M @ M.T

array([[25, 17],
       [17, 26]])

In [349]:
M.T @ M

array([[10,  7],
       [ 7, 41]])

In [350]:
a, b, c, d = sp.symbols('a b c c')

M = sp.Matrix([[a, b],
                [c, d]])

M

Matrix([
[a, b],
[c, c]])

In [351]:
M.T

Matrix([
[a, c],
[b, c]])

In [352]:
M @ M.T # symmetric

Matrix([
[a**2 + b**2, a*c + b*c],
[  a*c + b*c,    2*c**2]])

In [353]:
M.T @ M # symmetric

Matrix([
[a**2 + c**2,  a*b + c**2],
[ a*b + c**2, b**2 + c**2]])

##### Inverse

In [354]:
A = np.array([[1, 2],
              [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [355]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

##### Trace

In [356]:
A

array([[1, 2],
       [3, 4]])

In [357]:
np.trace(A)

5

##### Determinant

In [358]:
# scipy
la.det(A)

-2.0

In [359]:
# numpy 
np.linalg.det(A)

-2.0000000000000004

In [360]:
sp_A = sp.Matrix(A)
sp_A

Matrix([
[1, 2],
[3, 4]])

In [361]:
sp_A.det(), sp.det(sp_A)

(-2, -2)

### Solving Linear Systems

#### Linear Systems

A **linear system of equations** is a collection of linear equations:

$
a_{00}x_{0} + a_{01}x_{1} + \dots + a_{0n}x_{n} = b_{0} \\
a_{10}x_{0} + a_{11}x_{1} + \dots + a_{1n}x_{n} = b_{1} \\
\vdots \\
a_{m0}x_{0} + a_{m1}x_{1} + \dots + a_{mn}x_{n} = b_{m}
$

In matrix notation, a linear system is $Ax = b$ where

$A = 
\left[
\begin{matrix}
a_{00} & a_{01} & \dots & a_{0n} \\
a_{10} & a_{11} & \dots & a \\
\vdots & & & \vdots \\
a_{m0} & a_{m1} & \dots & a_{mn}
\end{matrix}
\right] ,
x = 
\left[
\begin{matrix}
x_{0}  \\
x_{1}  \\
\vdots  \\
x_{n}  
\end{matrix}
\right] ,
b = 
\left[
\begin{matrix}
b_{0}  \\
b_{1}  \\
\vdots  \\
b_{m}  
\end{matrix}
\right]
$

#### Gaussian Elimination

Perform elementary row operations to reduce the system to its row echelen form and then solve

###### Elementary Row Operations

1. Add $k$ times row $j$ to row $i$
2. Multiply row $i$ by scalar $k$
3. Switch rows $i$ and $j$

In [362]:
a, b, c, d, e, f, g, h, i, k = sp.symbols('a b c d e f g h i k')

A = sp.Matrix([[a, b, c],
               [d, e, f],
               [g, h, i]])

- Each of the **elementary row operations** is the result of matrix multiplication by an elementary matrix on the left.
- For example, $E_k$ is used to add 3 times row 2 to row 0

In [363]:
# add k times row 2 to row 0
Ek = sp.Matrix([[1, 0, k],
                [0, 1, 0],
                [0, 0, 1]])

In [364]:
Ek * A

Matrix([
[a + g*k, b + h*k, c + i*k],
[      d,       e,       f],
[      g,       h,       i]])

In [365]:
# multiply row 1 by -k
Ek = sp.Matrix([[1, 0, 0],
                [0, -k, 0],
                [0, 0, 1]])

In [366]:
Ek * A

Matrix([
[   a,    b,    c],
[-d*k, -e*k, -f*k],
[   g,    h,    i]])

In [367]:
# switch rows 1 and 2
Ek = sp.Matrix([[1, 0, 0],
                [0, 0, 1],
                [0, 1, 0]])

In [368]:
Ek * A

Matrix([
[a, b, c],
[g, h, i],
[d, e, f]])

###### Implementation

1. Add $k$ times row $j$ to row $i$
2. Multiply row $i$ by scalar $k$
3. Switch rows $i$ and $j$

###### $1.$ Add $k$ times row $j$ to row $i$

In [369]:
M = np.array([[1, 1],
              [3, 2]])
M

array([[1, 1],
       [3, 2]])

In [370]:
def add_row(A, k, i, j):
    'Add k times row j to row i in matrix A'
    n = A.shape[0]
    E = np.eye(n)
    if i == j:
        E[i, i] = k + 1
    else:
        E[i, j] = k 
    return E @ A

In [371]:
add_row(M, 2, 0, 1)

array([[7., 5.],
       [3., 2.]])

In [372]:
add_row(M, 3, 1, 1)

array([[ 1.,  1.],
       [12.,  8.]])

###### $2.$ Multiply row $i$ by scalar $k$

In [373]:
def scale_row(A, k, i):
    'Multiply row i by k'
    n = A.shape[0]
    E = np.eye(n)
    E[i, i] = k
    return E @ A

In [374]:
scale_row(M, 3, 0)

array([[3., 3.],
       [3., 2.]])

In [375]:
scale_row(np.array([[3, 1], [-2, 7]]), 3, 1)

array([[ 3.,  1.],
       [-6., 21.]])

In [376]:
A = np.array([[1, 1, 1],
              [1, -1, 0]])

In [377]:
scale_row(A, 5, 1)

array([[ 1.,  1.,  1.],
       [ 5., -5.,  0.]])

###### $3.$ Switch rows $i$ and $j$

In [378]:
def switch_rows(A, i, j):
    'Switch rows i and j in matrix A'
    n = A.shape[0]
    E = np.eye(n)
    E[i, i] = 0
    E[j, j] = 0
    E[i, j] = 1
    E[j, i] = 1
    print(E)
    return E @ A

In [379]:
A = np.array([[1, 1, 1],
              [1, -1, 0]])
A

array([[ 1,  1,  1],
       [ 1, -1,  0]])

In [380]:
switch_rows(A, 0, 1)

[[0. 1.]
 [1. 0.]]


array([[ 1., -1.,  0.],
       [ 1.,  1.,  1.]])