<a href="https://colab.research.google.com/github/PaulToronto/Howard-University-Coursera-Linear_Algebra-For-Data-Science-Specialization/blob/main/1_2_2_Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.2.2 Matrix Algebra

In [1]:
import numpy as np
import sympy as sym

## 1.2.2.1 Matrix Addition

### Definition

Two matrices are **equal** if they are the same shape and the corresponding entries are equal.

#### Example

Find $x$ so that the matrices $A$ and $B$ are equal.

In [2]:
x = sym.symbols('x')

In [3]:
A = sym.Matrix([[-1, 0, 5],
                [0, 5, 6]])
A

Matrix([
[-1, 0, 5],
[ 0, 5, 6]])

In [4]:
B = sym.Matrix([[-1, 0, x + 1],
                [0, 5, 6]])
B

Matrix([
[-1, 0, x + 1],
[ 0, 5,     6]])

In [5]:
sym.solve(x + 1 - 5)

[4]

The matrix $A$ is equal to $B$ when $x = 4$

### Definition: Matrix Addition

Let $A$ and $B$ be two $m \times n$ matrices. then the sum of the two matrices, denoted by $A + B$ is the $m \times n$ matrix, where the entries are $A + B$ are obtained by adding the corresponding entries of $A$ and $B$

#### Example

Find $A + B$

In [6]:
A = np.array([[-1, 0],
              [0, 5],
              [3, 0]])
A

array([[-1,  0],
       [ 0,  5],
       [ 3,  0]])

In [7]:
B = np.array([[1, 1],
              [3, -5],
              [1, 5]])
B

array([[ 1,  1],
       [ 3, -5],
       [ 1,  5]])

In [8]:
A + B

array([[0, 1],
       [3, 0],
       [4, 5]])

In [9]:
sym.Matrix(A) + sym.Matrix(B)

Matrix([
[0, 1],
[3, 0],
[4, 5]])

### Definition: Scalar Multiplication

Let $r$ be any real number (a **scalar**) and let $B$ be an $m \times n$ matrix. Then $rB$ is the $m \times n$ matrix determined by multiplying each entry of $B$ by the scalar $r$.

#### Remark

Let $A$ and $B$ be two matrices of the same size. Then

- $-A = (-1)A$
- $A - B = A + (-1)B$

#### Example

Given matrices $A$ and $B$ below, find $2B$ and find $A - 2B$.

In [10]:
A

array([[-1,  0],
       [ 0,  5],
       [ 3,  0]])

In [11]:
B

array([[ 1,  1],
       [ 3, -5],
       [ 1,  5]])

In [12]:
2 * B

array([[  2,   2],
       [  6, -10],
       [  2,  10]])

In [13]:
A - 2 * B

array([[ -3,  -2],
       [ -6,  15],
       [  1, -10]])

In [14]:
sym.Matrix(A) - 2 * sym.Matrix(B)

Matrix([
[-3,  -2],
[-6,  15],
[ 1, -10]])

### Theorem

Let $A$, $B$, and $C$ be three matrices of the same size. Let $r$ and $s$ be two scalars. Then

1. $A + B = B + A$ 
    - Commutative property of addition
2. $A + (B + C) = (A + B) + C$ 
    - Associative property of addition
3. $A + O = A$, where $O$ is the **zero matrix**
    - Additive identity property
4. $r(A + B) = rA + rB$ 
    - Distributive property
5. $(r + s)A = rA + sA$ 
    - Distributive property
6. $(rs)A = r(sA)$ 
    - Associative property of multiplication

## 1.2.2.2 Matrix Multiplication