<a href="https://colab.research.google.com/github/PaulToronto/Howard-University-Coursera-Linear-Algebra-For-Data-Science-Specialization/blob/main/1_2_2_Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.2.2 Matrix Algebra

In [1]:
import numpy as np
import sympy as sym
import scipy as sci

## 1.2.2.1 Matrix Addition

### Definition

Two matrices are **equal** if they are the same shape and the corresponding entries are equal.

#### Example

Find $x$ so that the matrices $A$ and $B$ are equal.

In [2]:
x = sym.symbols('x')

In [3]:
A = sym.Matrix([[-1, 0, 5],
                [0, 5, 6]])
A

Matrix([
[-1, 0, 5],
[ 0, 5, 6]])

In [4]:
B = sym.Matrix([[-1, 0, x + 1],
                [0, 5, 6]])
B

Matrix([
[-1, 0, x + 1],
[ 0, 5,     6]])

In [5]:
sym.solve(x + 1 - 5)

[4]

$\therefore$ The matrix $A$ is equal to $B$ when $x = 4$

### Definition: Matrix Addition

Let $A$ and $B$ be two $m \times n$ matrices. then the sum of the two matrices, denoted by $A + B$ is the $m \times n$ matrix, where the entries are $A + B$ are obtained by adding the corresponding entries of $A$ and $B$

#### Example

Find $A + B$

In [6]:
A = np.array([[-1, 0],
              [0, 5],
              [3, 0]])
A

array([[-1,  0],
       [ 0,  5],
       [ 3,  0]])

In [7]:
B = np.array([[1, 1],
              [3, -5],
              [1, 5]])
B

array([[ 1,  1],
       [ 3, -5],
       [ 1,  5]])

In [8]:
A + B

array([[0, 1],
       [3, 0],
       [4, 5]])

In [9]:
sym.Matrix(A) + sym.Matrix(B)

Matrix([
[0, 1],
[3, 0],
[4, 5]])

### Definition: Scalar Multiplication

Let $r$ be any real number (a **scalar**) and let $B$ be an $m \times n$ matrix. Then $rB$ is the $m \times n$ matrix determined by multiplying each entry of $B$ by the scalar $r$.

#### Remark

Let $A$ and $B$ be two matrices of the same size. Then

- $-A = (-1)A$
- $A - B = A + (-1)B$

#### Example

Given matrices $A$ and $B$ below, find $2B$ and find $A - 2B$.

In [10]:
A

array([[-1,  0],
       [ 0,  5],
       [ 3,  0]])

In [11]:
B

array([[ 1,  1],
       [ 3, -5],
       [ 1,  5]])

In [12]:
2 * B

array([[  2,   2],
       [  6, -10],
       [  2,  10]])

In [13]:
A - 2 * B

array([[ -3,  -2],
       [ -6,  15],
       [  1, -10]])

In [14]:
sym.Matrix(A) - 2 * sym.Matrix(B)

Matrix([
[-3,  -2],
[-6,  15],
[ 1, -10]])

### Theorem

Let $A$, $B$, and $C$ be three matrices of the same size. Let $r$ and $s$ be two scalars. Then

1. $A + B = B + A$
    - Commutative property of addition
2. $A + (B + C) = (A + B) + C$
    - Associative property of addition
3. $A + O = A$, where $O$ is the **zero matrix**
    - Additive identity property
4. $r(A + B) = rA + rB$
    - Distributive property
5. $(r + s)A = rA + sA$
    - Distributive property
6. $(rs)A = r(sA)$
    - Associative property of multiplication

## 1.2.2.2 Matrix Multiplication

### Definition

Let
$
u = \left(\begin{matrix}
u_{1} \\
u_{2} \\
\vdots \\
u_{n}
\end{matrix}\right)
$
and
$
v = \left(\begin{matrix}
v_{1} \\
v_{2} \\
\vdots \\
v_{n}
\end{matrix}\right)
$
be two column vectors. Then the **inner product** or **dot product** of $u$ and $v$ is denoted by $u^{T} \cdot v$.

$
\begin{align}
u^{T} \cdot v
&=
\left(\begin{matrix}
    u_{1} & u_{2} & \dots & u_{n}
\end{matrix}\right)
\cdot
\left(\begin{matrix}
    v_{1} \\
    v_{2} \\
    \vdots \\
    v_{n}
\end{matrix}\right) \\
&=
u_{1}v_{1} + u_{2}v_{2} + \dots + u_{n}v_{n}
\end{align}
$

#### Example

In [15]:
u = sym.Matrix([[1], [0], [-1], [5]])
v = sym.Matrix([[2], [1], [0], [-1]])

In [16]:
u.T * v

Matrix([[-3]])

In [17]:
u.dot(v)

-3

In [18]:
sum([u[i] * v[i] for i in range(4)])

-3

#### Example

We want to find $C = A \cdot B =
\left(\begin{matrix}
1 & 1 \\
1 & 0
\end{matrix}\right) \cdot
\left(\begin{matrix}
0 & 1 \\
1 & 2
\end{matrix}\right)$

$C_{ij}$ is obtained by mutliplying the $i^{th}$ row of $A$ by the $j^{th}$ row if $B$

$
\begin{align}
C_{11}
&=
\left(\begin{matrix}
    1 & 1
\end{matrix}\right)
\cdot
\left(\begin{matrix}
    0 \\
    1
\end{matrix}\right) \\
&= 1 \cdot 0 + 1 \cdot 1 \\
&= 1
\end{align}
$

$
\begin{align}
C_{12}
&=
\left(\begin{matrix}
    1 & 1
\end{matrix}\right)
\cdot
\left(\begin{matrix}
    1 \\
    2
\end{matrix}\right) \\
&= 1 \cdot 1 + 1 \cdot 2 \\
&= 1 + 2 \\
&= 3
\end{align}
$

$
\begin{align}
C_{21}
&=
\left(\begin{matrix}
    1 & 0
\end{matrix}\right)
\cdot
\left(\begin{matrix}
    0 \\
    1
\end{matrix}\right) \\
&= 1 \cdot 0 + 0 \cdot 1 \\
&= 0
\end{align}
$

$
\begin{align}
C_{22}
&=
\left(\begin{matrix}
    1 & 0
\end{matrix}\right)
\cdot
\left(\begin{matrix}
    1 \\
    2
\end{matrix}\right) \\
&= 1 \cdot 1 + 2 \cdot 2 \\
&= 1
\end{align}
$


$
\therefore
C =
\left(\begin{matrix}
1 & 3 \\
0 & 1
\end{matrix}\right)
$

In [19]:
A = sym.Matrix([[1, 1], [1, 0]])
B = sym.Matrix([[0, 1], [1, 2]])

In [20]:
A * B

Matrix([
[1, 3],
[0, 1]])

In [21]:
A @ B

Matrix([
[1, 3],
[0, 1]])

### Definition: Matrix Multiplication

Let $A$ be and $m \times n$ matrix with rows $r_{1}, r_{2}, \dots, r_{m}$ and let $B$ be an $n \times p$ matrix with columns $c_{1}, c_{2}, \dots, c_{p}$.

The the **product** of the two matrices, denoted by $A \cdot B$ is the $m \times p$ matrix, where the entry in the $i^{th}$ row and $j^{th}$ column is given by the dot product $r_{i} \cdot c_{j}$, that is the dot product of the $i^{th}$ row of matrix $A$ and the $j^{th}$ column of matrix $B$.

#### Observation

1. Matrix multiplication is **not commutative**. It may be the case that $A \cdot B$ is not equal to $B \cdot A$.
2. In fact, it is possible that $A \cdot B$ is defined, but $B \cdot A$ is not defined.
3. If $A$ and $B$ are square matrices of the same size, then both $A \cdot B$ and $B \cdot A$ exist, but they might not be equal to each other.

##### Example

###### Numpy

In [22]:
A = np.array([[-1, 0], [0, 5]])
B = np.array([[1, 1], [3, -5]])

In [23]:
A

array([[-1,  0],
       [ 0,  5]])

In [24]:
B

array([[ 1,  1],
       [ 3, -5]])

In [25]:
A.dot(B)

array([[ -1,  -1],
       [ 15, -25]])

In [26]:
A * B # element-wise, not matrix multiplication

array([[ -1,   0],
       [  0, -25]])

In [27]:
A @ B

array([[ -1,  -1],
       [ 15, -25]])

In [28]:
B @ A

array([[ -1,   5],
       [ -3, -25]])

###### Sympy

In [29]:
A = sym.Matrix(A)
B = sym.Matrix(B)

In [30]:
A

Matrix([
[-1, 0],
[ 0, 5]])

In [31]:
B

Matrix([
[1,  1],
[3, -5]])

In [32]:
A @ B

Matrix([
[-1,  -1],
[15, -25]])

In [33]:
A * B

Matrix([
[-1,  -1],
[15, -25]])

In [34]:
B * A

Matrix([
[-1,   5],
[-3, -25]])

From this example, we can see that $A \cdot B \ne B \cdot A$

##### Example

Let
$I_{2} =
\left(\begin{matrix}
1 & 0 \\
0 & 1
\end{matrix}\right)
$ and let
$
A =
\left(\begin{matrix}
1 & 2 \\
3 & 4
\end{matrix}\right)
$.

In [35]:
I_2 = np.array([[1, 0], [0, 1]])
A = np.array([[1, 2], [3, 4]])

In [36]:
I_2 @ A

array([[1, 2],
       [3, 4]])

In [37]:
A @ I_2

array([[1, 2],
       [3, 4]])

Note that $I_{2} \cdot A = A$ and also that $A \cdot I_{2} = A$.

#### Example

In [38]:
a, b, c, d = sym.symbols('a b c d')
A = sym.Matrix([[a, b], [c, d]])
I_2 = sym.Matrix(I_2)

In [39]:
A

Matrix([
[a, b],
[c, d]])

In [40]:
I_2

Matrix([
[1, 0],
[0, 1]])

In [41]:
A * I_2 == A, I_2 * A == A

(True, True)

In [42]:
A @ I_2 == A, I_2 @ A == A

(True, True)

##### Remark

The matrix
$I_{2} =
\left(\begin{matrix}
1 & 0 \\
0 & 1
\end{matrix}\right)
$
acts as an identity elment for any $2 \times 2$ matrix $A$. In fact, it can be shown that $I_{2} \cdot A = A \cdot I_{2} = A$ for all $2 \times 2$ matrices.

#### Theorem

Let $I_n$ by the $n \times n$ matrix defined by
$I_{n} =
\left(\begin{matrix}
1 & 0 & 0 & \dots & 0 \\
0 & 1 & 0 & \dots & 0 \\
0 & 0 & 1 & \dots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \dots & 1
\end{matrix}\right)
$

Then for any $n \times n$ matrix $A$,

$I_{n} \cdot A$ = $A \cdot I_{n} = A$.

##### Definition: Identity Matrix

The matrix $I_{n}$ is called the **identity matrix** for the set of $n \times n$ matrrices.

We will simply write $I$ for $I_{n}$ when this is unlikely to cause confusion.

## 1.2.2.3 A Practical Example of Matrix Multiplication

### Problem

- You only have time to visit one store
- You have choice of three supermarkets: A, B, C
- You need: Broccoli (2.5 pounds), tomatoes (4 pounds), carrots (2 pounds)
- Your goal is to spend as little money as possible
- Prices, per pound, are shown in the table below


|Supermarket|Broccoli|Tomatoes|Carrots|
|-|-|-|-|
|A|\$1.49|\$3.99|\$2.49|
|B|\$1.69|\$2.49|\$1.69|
|C|\$1.04|\$3.52|\$1.28|


To find the best shopping option, simply find $P \cdot A$ and pick the smallest number in the product.

$$
\begin{align}
P \cdot A &=
\left(\begin{matrix}
1.49 & 3.99 & 2.49 \\
1.69 & 2.49 & 1.69 \\
1.04 & 3.52 & 1.28
\end{matrix}\right)
\left(\begin{matrix}
2.5 \\
4 \\
2
\end{matrix}\right) \\ &=
\left(\begin{matrix}
24.665 \\
17.565 \\
19.24
\end{matrix}\right)
\end{align}
$$

$\therefore$ I should go to supermarket B, where it will cost about $\$17.57$ for the items I need.

In [43]:
# Prices, per pound
P = np.array([[1.49, 3.99, 2.49],
              [1.69, 2.49, 1.69],
              [1.04, 3.52, 1.28]])

# Qauntities needed
Q = np.array([2.5, 4, 2]).reshape(3, 1)

In [44]:
P @ Q

array([[24.665],
       [17.565],
       [19.24 ]])

In [45]:
P.dot(Q)

array([[24.665],
       [17.565],
       [19.24 ]])

In [46]:
P = sym.Matrix(P)
Q = sym.Matrix(Q)
P * Q

Matrix([
[24.665],
[17.565],
[ 19.24]])

## 1.2.2.4 Using Matrix Algebra in Python

In [47]:
L = np.linspace(-8, 8, 9)
M = L.reshape(3, 3)
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [48]:
N = np.array([[4, 1, -7],
              [-6, -6, -6],
              [-3, 7, 3]])
N

array([[ 4,  1, -7],
       [-6, -6, -6],
       [-3,  7,  3]])

In [49]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 2, -3],
              [0, 1, 6]])

### Multiplying Matrices

#### NumPy

In [50]:
np.matmul(M, N)

array([[ 16.,   0.,  80.],
       [-14.,  12.,  20.],
       [-44.,  24., -40.]])

In [51]:
np.dot(M, N)

array([[ 16.,   0.,  80.],
       [-14.,  12.,  20.],
       [-44.,  24., -40.]])

In [52]:
M.dot(N)

array([[ 16.,   0.,  80.],
       [-14.,  12.,  20.],
       [-44.,  24., -40.]])

In [53]:
M @ N

array([[ 16.,   0.,  80.],
       [-14.,  12.,  20.],
       [-44.,  24., -40.]])

In [54]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
B

array([[ 7,  2, -3],
       [ 0,  1,  6]])

In [56]:
B.T

array([[ 7,  0],
       [ 2,  1],
       [-3,  6]])

In [57]:
A.shape, B.T.shape

((2, 3), (3, 2))

In [58]:
A.dot(B.T)

array([[ 2, 20],
       [20, 41]])

#### SymPy

In [59]:
sM = sym.Matrix(M)
sN = sym.Matrix(N)
sA = sym.Matrix(A)
sB = sym.Matrix(B)

In [60]:
sM * sN

Matrix([
[ 16.0,    0,  80.0],
[-14.0, 12.0,  20.0],
[-44.0, 24.0, -40.0]])

In [61]:
sA * sB.T

Matrix([
[ 2, 20],
[20, 41]])

### Calculating Matrix Determinant

#### NumPy

In [62]:
np.linalg.det(M)

0.0

In [63]:
np.linalg.det(N)

552.0000000000003

#### SciPy

In [64]:
import scipy.linalg as la

In [65]:
la.det(M)

0.0

In [66]:
la.det(N)

552.0

#### SymPy

In [67]:
sym.det(sM)

0

In [68]:
sM.det()

0

In [69]:
sym.det(sN)

552

In [70]:
sN.det()

552

### Inverse of a Matrix

#### NumPy

In [71]:
np.linalg.inv(N)

array([[ 0.04347826, -0.0942029 , -0.08695652],
       [ 0.06521739, -0.01630435,  0.11956522],
       [-0.10869565, -0.05615942, -0.0326087 ]])

#### SymPy

In [72]:
sN.inv()

Matrix([
[ 1/23, -13/138, -2/23],
[ 3/46,  -3/184, 11/92],
[-5/46, -31/552, -3/92]])

In [73]:
sN.inv().evalf()

Matrix([
[0.0434782608695652, -0.0942028985507246, -0.0869565217391304],
[0.0652173913043478,  -0.016304347826087,   0.119565217391304],
[-0.108695652173913, -0.0561594202898551, -0.0326086956521739]])

In [74]:
sN**-1

Matrix([
[ 1/23, -13/138, -2/23],
[ 3/46,  -3/184, 11/92],
[-5/46, -31/552, -3/92]])

## 1.2.2.5 Practice Quiz

In [75]:
M = np.array([[-3, 1, 4], [2, 5, 9], [-1, 8, 6]])
M

array([[-3,  1,  4],
       [ 2,  5,  9],
       [-1,  8,  6]])

In [76]:
M + 3

array([[ 0,  4,  7],
       [ 5,  8, 12],
       [ 2, 11,  9]])

## 1.2.2.6 Quiz

In [77]:
A = np.array([[3, -1], [2, -2]])
A

array([[ 3, -1],
       [ 2, -2]])

In [78]:
B = np.array([[1, 2, -1],
              [0, 2, 7]])
B

array([[ 1,  2, -1],
       [ 0,  2,  7]])

In [79]:
(2 * A) @ B

array([[  6,   8, -20],
       [  4,   0, -32]])

In [80]:
sp_A = sym.Matrix(A)
sp_A

Matrix([
[3, -1],
[2, -2]])

In [81]:
sp_B = sym.Matrix(B)
sp_B

Matrix([
[1, 2, -1],
[0, 2,  7]])

In [82]:
2 * sp_A * sp_B

Matrix([
[6, 8, -20],
[4, 0, -32]])