<a href="https://colab.research.google.com/github/PaulToronto/Howard-University-Coursera-Linear-Algebra-For-Data-Science-Specialization/blob/main/1_2_1_Using_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.2.1 Using Linear Algebra

In [206]:
import numpy as np
import random
import sympy as sp
import matplotlib.pyplot as plt

## 1.2.1.1 Introduction to Linear Algebra Functions in Python

In [207]:
M = np.linspace(-8, 8, 9).reshape(3, 3)
N = np.random.randint(-8, 8, size=(3, 3))
O = 2*N

sp_M = sp.Matrix(M)
sp_N = sp.Matrix(N)
sp_O = sp.Matrix(O)

v1 = np.array([1, 3, 5, 7])
v2 = np.array([2, 4, 6, 8])
v3 = np.array([-2, 5, 1, 3])

sp_v1 = sp.Matrix(v1)
sp_v2 = sp.Matrix(v2)
sp_v3 = sp.Matrix(v3)

In [208]:
M, sp_M, N, sp_N, O, sp_O

(array([[-8., -6., -4.],
        [-2.,  0.,  2.],
        [ 4.,  6.,  8.]]),
 Matrix([
 [-8.0, -6.0, -4.0],
 [-2.0,    0,  2.0],
 [ 4.0,  6.0,  8.0]]),
 array([[-4, -4,  1],
        [ 0, -5,  0],
        [ 7, -8, -8]]),
 Matrix([
 [-4, -4,  1],
 [ 0, -5,  0],
 [ 7, -8, -8]]),
 array([[ -8,  -8,   2],
        [  0, -10,   0],
        [ 14, -16, -16]]),
 Matrix([
 [-8,  -8,   2],
 [ 0, -10,   0],
 [14, -16, -16]]))

In [209]:
v1

array([1, 3, 5, 7])

In [210]:
sp_v1

Matrix([
[1],
[3],
[5],
[7]])

### `dot()` for two vectors

The `dot` function calculates the **dot product** of two vectors.

In [211]:
v1, v2

(array([1, 3, 5, 7]), array([2, 4, 6, 8]))

In [212]:
total = 0;
for i in range(4):
    total += v1[i] * v2[i]

total

100

In [213]:
sum([v1[i] * v2[i] for i in range(4)])

100

In [214]:
np.dot(v1, v2)

100

In [215]:
v1.dot(v2)

100

#### Sympy

In [216]:
sp.DotProduct(sp_v1, sp_v2)

DotProduct(Matrix([
[1],
[3],
[5],
[7]]), Matrix([
[2],
[4],
[6],
[8]]))

In [217]:
sp.DotProduct(sp_v1, sp_v2).simplify()

100

In [218]:
sp_v1.dot(sp_v2)

100

### `dot()` for two matrices

This is matrix multiplication

In [219]:
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [220]:
N

array([[-4, -4,  1],
       [ 0, -5,  0],
       [ 7, -8, -8]])

In [221]:
N[0,:], N[1, :], N[2,:] # rows of N

(array([-4, -4,  1]), array([ 0, -5,  0]), array([ 7, -8, -8]))

In [222]:
N[:,0], N[:,1], N[:,2] # columns of N

(array([-4,  0,  7]), array([-4, -5, -8]), array([ 1,  0, -8]))

In [223]:
np.dot(N, M)

array([[  44.,   30.,   16.],
       [  10.,    0.,  -10.],
       [ -72.,  -90., -108.]])

In [224]:
np.dot(M, N)

array([[   4.,   94.,   24.],
       [  22.,   -8.,  -18.],
       [  40., -110.,  -60.]])

In [225]:
N_dot_M = np.zeros((3, 3))

for i in range(3):
    for j in range(3):
        row_N = N[i,:]
        col_M = M[:,j]
        N_dot_M[i,j] = np.dot(row_N, col_M)

N_dot_M

array([[  44.,   30.,   16.],
       [  10.,    0.,  -10.],
       [ -72.,  -90., -108.]])

In [226]:
N.dot(M)

array([[  44.,   30.,   16.],
       [  10.,    0.,  -10.],
       [ -72.,  -90., -108.]])

In [227]:
N

array([[-4, -4,  1],
       [ 0, -5,  0],
       [ 7, -8, -8]])

In [228]:
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [229]:
np.matmul(N, M) # also the dot product

array([[  44.,   30.,   16.],
       [  10.,    0.,  -10.],
       [ -72.,  -90., -108.]])

In [230]:
N @ M # also the dot product

array([[  44.,   30.,   16.],
       [  10.,    0.,  -10.],
       [ -72.,  -90., -108.]])

In [231]:
N * M # element-wise mutliplication

array([[ 32.,  24.,  -4.],
       [ -0.,  -0.,   0.],
       [ 28., -48., -64.]])

#### SymPy

In [232]:
N.dot(M)

array([[  44.,   30.,   16.],
       [  10.,    0.,  -10.],
       [ -72.,  -90., -108.]])

In [233]:
np.matmul(N, M)

array([[  44.,   30.,   16.],
       [  10.,    0.,  -10.],
       [ -72.,  -90., -108.]])

In [234]:
sp_N

Matrix([
[-4, -4,  1],
[ 0, -5,  0],
[ 7, -8, -8]])

In [235]:
sp_M

Matrix([
[-8.0, -6.0, -4.0],
[-2.0,    0,  2.0],
[ 4.0,  6.0,  8.0]])

In [236]:
sp_N * sp_M

Matrix([
[ 44.0,  30.0,   16.0],
[ 10.0,     0,  -10.0],
[-72.0, -90.0, -108.0]])

In [237]:
sp_N @ sp_M

Matrix([
[ 44.0,  30.0,   16.0],
[ 10.0,     0,  -10.0],
[-72.0, -90.0, -108.0]])

In [238]:
sp.matrices.dense.matrix_multiply_elementwise(sp_N, sp_M)

Matrix([
[32.0,  24.0,  -4.0],
[   0,     0,     0],
[28.0, -48.0, -64.0]])

### `linalg.multi_dot()`

In [239]:
np.linalg.multi_dot([M, N, O])

array([[  304., -1356.,  -376.],
       [ -428.,   192.,   332.],
       [-1160.,  1740.,  1040.]])

In [240]:
M.dot(N).dot(O)

array([[  304., -1356.,  -376.],
       [ -428.,   192.,   332.],
       [-1160.,  1740.,  1040.]])

#### SymPy

In [241]:
sp_M * sp_N * sp_O

Matrix([
[  304.0, -1356.0, -376.0],
[ -428.0,   192.0,  332.0],
[-1160.0,  1740.0, 1040.0]])

### `vdot()`

In [242]:
v1, v2

(array([1, 3, 5, 7]), array([2, 4, 6, 8]))

In [243]:
np.vdot(v1, v2), np.dot(v1, v2)

(100, 100)

#### SymPy

In [244]:
sp_v1.dot(sp_v2)

100

### `inner()`

Returns the inner product of two arrays

In [245]:
v3, v1

(array([-2,  5,  1,  3]), array([1, 3, 5, 7]))

In [246]:
np.inner(v3, v1)

39

In [247]:
np.dot(v3, v1)

39

#### SymPy

In [248]:
sp_v3.dot(sp_v1), sp_v1.dot(sp_v3)

(39, 39)

In [249]:
sp.DotProduct(sp_v3, sp_v1).simplify()

39

### `matmul()`

In [250]:
np.matmul(M, N)

array([[   4.,   94.,   24.],
       [  22.,   -8.,  -18.],
       [  40., -110.,  -60.]])

In [251]:
np.dot(M, N)

array([[   4.,   94.,   24.],
       [  22.,   -8.,  -18.],
       [  40., -110.,  -60.]])

#### SymPy

In [252]:
sp_M * sp_N

Matrix([
[ 4.0,   94.0,  24.0],
[22.0,   -8.0, -18.0],
[40.0, -110.0, -60.0]])

In [253]:
sp_M @ sp_N

Matrix([
[ 4.0,   94.0,  24.0],
[22.0,   -8.0, -18.0],
[40.0, -110.0, -60.0]])

In [254]:
M.dot(N)

array([[   4.,   94.,   24.],
       [  22.,   -8.,  -18.],
       [  40., -110.,  -60.]])

### `linalg.matrix_power()`

In [255]:
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [256]:
np.linalg.matrix_power(M, 3)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [257]:
M.dot(M).dot(M)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [258]:
np.linalg.multi_dot([M, M, M])

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [259]:
np.matmul(np.matmul(M, M), M)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

#### SymPy

In [260]:
sp_M**3

Matrix([
[-576.0, -432.0, -288.0],
[-144.0,      0,  144.0],
[ 288.0,  432.0,  576.0]])

In [261]:
sp_M * sp_M * sp_M

Matrix([
[-576.0, -432.0, -288.0],
[-144.0,      0,  144.0],
[ 288.0,  432.0,  576.0]])

### `linalg.eig()`

Returns the eigenvalues and eigenvectors of a matrix

In [262]:
O

array([[ -8,  -8,   2],
       [  0, -10,   0],
       [ 14, -16, -16]])

In [263]:
eig_vals, eig_vects = np.linalg.eig(O)

In [264]:
eig_vals

array([ -5.36675042, -18.63324958, -10.        ])

In [265]:
eig_vects

array([[ 0.60483985, -0.18484794,  0.66666667],
       [ 0.        ,  0.        ,  0.33333333],
       [ 0.79634714,  0.98276713,  0.66666667]])

#### SymPy

In [266]:
sp_O.eigenvals()

{-10: 1, -12 - 2*sqrt(11): 1, -12 + 2*sqrt(11): 1}

In [267]:
2, 10 - 2 * np.sqrt(5), 2 * np.sqrt(5) + 10

(2, 5.52786404500042, 14.47213595499958)

In [268]:
for eig_val in list(sp_O.eigenvals()):
    print(eig_val.evalf())

-10.0000000000000
-18.6332495807108
-5.36675041928920


In [269]:
# takes too long to run
# eig_vects = sp_O.eigenvects()

### `linalg.eigh()`

Returns eigenvalues and eigenvectors of a complex Hermition matrix or a real symmetric matrix

In [270]:
eigh_vals, eigh_vects = np.linalg.eigh(N)

In [271]:
eigh_vals

array([-17.05925527,  -4.44139317,   4.50064844])

In [272]:
eigh_vects

array([[-0.40783339, -0.74135654, -0.53297506],
       [ 0.50474573, -0.66948129,  0.54500143],
       [ 0.7608572 ,  0.0467471 , -0.64723337]])

### `linalg.det()`

Returns the determinant of a matrix

In [273]:
np.linalg.det(M), np.linalg.det(N), np.linalg.det(O)

(0.0, -124.99999999999994, -999.9999999999998)

#### SymPy

In [274]:
sp_M.det(), sp_N.det(), sp_O.det()

(0, -125, -1000)

### `linalg.inv()`

Returns the inverse of a matrix

In [275]:
N

array([[-4, -4,  1],
       [ 0, -5,  0],
       [ 7, -8, -8]])

In [276]:
np.linalg.inv(N)

array([[-3.2000000e-01,  3.2000000e-01, -4.0000000e-02],
       [-0.0000000e+00, -2.0000000e-01, -1.2952602e-17],
       [-2.8000000e-01,  4.8000000e-01, -1.6000000e-01]])

In [277]:
np.matmul(N, np.linalg.inv(N))

array([[ 1.00000000e+00, -1.11022302e-16,  2.77555756e-17],
       [ 0.00000000e+00,  1.00000000e+00,  6.47630098e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [278]:
N.dot(np.linalg.inv(N))

array([[ 1.00000000e+00, -1.11022302e-16,  2.77555756e-17],
       [ 0.00000000e+00,  1.00000000e+00,  6.47630098e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

#### SymPy

In [279]:
sp_N**-1

Matrix([
[-8/25,  8/25, -1/25],
[    0,  -1/5,     0],
[-7/25, 12/25, -4/25]])

In [280]:
(sp_N**-1).evalf()

Matrix([
[-0.32, 0.32, -0.04],
[    0, -0.2,     0],
[-0.28, 0.48, -0.16]])

In [281]:
sp_N * sp_N**-1

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

## 1.2.1.2 Using Matrices in Python

### Building Matrices Using Numpy

In [282]:
L = np.linspace(0, 120, 25)
L

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100., 105.,
       110., 115., 120.])

In [283]:
M = L.reshape(5, 5)
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [284]:
R = np.random.randint(-5, 4, size=(4, 4))
R

array([[-4, -4, -1, -4],
       [-4,  3,  0, -1],
       [-3, -3,  0, -2],
       [ 3, -2,  2, -3]])

### Building Matrices Using SymPy

In [285]:
sp.Matrix([[1, -1], [3, 4], [0, 2]])

Matrix([
[1, -1],
[3,  4],
[0,  2]])

In [286]:
sp_M = sp.Matrix(M)
sp_M

Matrix([
[    0,   5.0,  10.0,  15.0,  20.0],
[ 25.0,  30.0,  35.0,  40.0,  45.0],
[ 50.0,  55.0,  60.0,  65.0,  70.0],
[ 75.0,  80.0,  85.0,  90.0,  95.0],
[100.0, 105.0, 110.0, 115.0, 120.0]])

In [287]:
sp_R = sp.Matrix(R)
sp_R

Matrix([
[-4, -4, -1, -4],
[-4,  3,  0, -1],
[-3, -3,  0, -2],
[ 3, -2,  2, -3]])

### Accessing Matrix Entries: NumPy and SymPy

In [288]:
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [289]:
# first row
M[0]

array([ 0.,  5., 10., 15., 20.])

In [290]:
M[0,:] # also first row

array([ 0.,  5., 10., 15., 20.])

In [291]:
# first rown
sp_M.row(0)

Matrix([[0, 5.0, 10.0, 15.0, 20.0]])

In [292]:
# also first row
sp_M[0, :]

Matrix([[0, 5.0, 10.0, 15.0, 20.0]])

In [293]:
# last row
M[-1]

array([100., 105., 110., 115., 120.])

In [294]:
# last row
sp_M.row(-1)

Matrix([[100.0, 105.0, 110.0, 115.0, 120.0]])

In [295]:
#first column
M[:,0]

array([  0.,  25.,  50.,  75., 100.])

In [296]:
sp_M.col(0)

Matrix([
[    0],
[ 25.0],
[ 50.0],
[ 75.0],
[100.0]])

In [297]:
# last column
M[:,-1]

array([ 20.,  45.,  70.,  95., 120.])

In [298]:
sp_M.col(-1)

Matrix([
[ 20.0],
[ 45.0],
[ 70.0],
[ 95.0],
[120.0]])

In [299]:
# first 3 rows
M[0:3]

array([[ 0.,  5., 10., 15., 20.],
       [25., 30., 35., 40., 45.],
       [50., 55., 60., 65., 70.]])

In [300]:
# first 3 rows
sp_M[0:3,:]

Matrix([
[   0,  5.0, 10.0, 15.0, 20.0],
[25.0, 30.0, 35.0, 40.0, 45.0],
[50.0, 55.0, 60.0, 65.0, 70.0]])

In [301]:
# third and fourth columns
M[:,2:4]

array([[ 10.,  15.],
       [ 35.,  40.],
       [ 60.,  65.],
       [ 85.,  90.],
       [110., 115.]])

In [302]:
sp_M[:, 2:4]

Matrix([
[ 10.0,  15.0],
[ 35.0,  40.0],
[ 60.0,  65.0],
[ 85.0,  90.0],
[110.0, 115.0]])

In [303]:
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [304]:
# first 3 rows, 2nd, 3rd and 4th columns
M[:3, 1:4]

array([[ 5., 10., 15.],
       [30., 35., 40.],
       [55., 60., 65.]])

In [305]:
sp_M[:3, 1:4]

Matrix([
[ 5.0, 10.0, 15.0],
[30.0, 35.0, 40.0],
[55.0, 60.0, 65.0]])

In [306]:
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [307]:
# first 3 rows, 2nd and 4th columns
M[:3, (1, 3)]

array([[ 5., 15.],
       [30., 40.],
       [55., 65.]])

In [308]:
sp_M[:3, (1, 3)]

Matrix([
[ 5.0, 15.0],
[30.0, 40.0],
[55.0, 65.0]])

In [309]:
# the entry at the intersection of
# the 2nd row and the 2nd column
M[1, 1]

30.0

In [310]:
sp_M[1,1]

30.0000000000000

## 1.2.1.3 Solving Linear Equations Using Python

### Example

$
\begin{align}
4x + 3y + 2x &= 25 \\
-2x + 2y + 3z &= -10 \\
3x - 5y + 2z &= -4
\end{align}
$

#### Solve Using the Inverse Method

In a nutshell, the solution is found by multiplying the inverse of the coefficent matrix, $M^{-1}$ by the column matrix, $K$.

Let $V$ be the solution, then

$V = M^{-1} * K$

Details about why this equation works are shown in this notebook.

In [311]:
# M is the coefficient matrix
M = np.array([[4, 3, 2],
              [-2, 2, 3],
              [3, -5, 2]])
M

array([[ 4,  3,  2],
       [-2,  2,  3],
       [ 3, -5,  2]])

In [312]:
# K is the column matrix
K = np.array([[25],
              [-10],
              [-4]])
K

array([[ 25],
       [-10],
       [ -4]])

In [313]:
V = np.array([['x'],
              ['y'],
              ['z']])
V

array([['x'],
       ['y'],
       ['z']], dtype='<U1')

The system of linear equations in this example can be written as:

$
M * V = K \\
\implies
M^{-1} * M * V = M^{-1} * K \\
\implies
I * V = M^{-1} * K \\
\implies
V = M^{-1} * K
$

In [314]:
np.linalg.inv(M).dot(K)

array([[ 5.],
       [ 3.],
       [-2.]])

##### Sympy

In [315]:
sp_M = sp.Matrix(M)
sp_M

Matrix([
[ 4,  3, 2],
[-2,  2, 3],
[ 3, -5, 2]])

In [316]:
sp_K = sp.Matrix(K)
sp_K

Matrix([
[ 25],
[-10],
[ -4]])

In [317]:
sp_M**-1 * sp_K

Matrix([
[ 5],
[ 3],
[-2]])

##### Symbolic summary of this method

In [318]:
x, y, z = sp.symbols('x y z')
m_11, m_12, m_13 = sp.symbols('m_11 m_12 m_13')
m_21, m_22, m_23 = sp.symbols('m_21 m_22 m_23')
m_31, m_32, m_33 = sp.symbols('m_31 m_32 m_33')
k_1, k_2, k_3 = sp.symbols('k_1 k_2 k_3')

In [319]:
V = sp.Matrix([[x], [y], [z]])
V

Matrix([
[x],
[y],
[z]])

In [320]:
M = sp.Matrix([[m_11, m_12, m_13],
               [m_21, m_22, m_23],
               [m_31, m_32, m_33]])
M

Matrix([
[m_11, m_12, m_13],
[m_21, m_22, m_23],
[m_31, m_32, m_33]])

In [321]:
K = sp.Matrix([[k_1], [k_2], [k_3]])
K

Matrix([
[k_1],
[k_2],
[k_3]])

In [322]:
sp.Eq(M * V, K)

Eq(Matrix([
[m_11*x + m_12*y + m_13*z],
[m_21*x + m_22*y + m_23*z],
[m_31*x + m_32*y + m_33*z]]), Matrix([
[k_1],
[k_2],
[k_3]]))

In [323]:
sp.Eq(V, M**-1 * K)

Eq(Matrix([
[x],
[y],
[z]]), Matrix([
[ k_1*(m_22*m_33 - m_23*m_32)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_2*(-m_12*m_33 + m_13*m_32)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_3*(m_12*m_23 - m_13*m_22)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31)],
[k_1*(-m_21*m_33 + m_23*m_31)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_2*(m_11*m_33 - m_13*m_31)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_3*(-m_11*m_23 + m_13*m_21)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31)],
[ k_1*(m_21*m_32 - m_22*m_31)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_2*(-m_11*m_32 + m_12*m_31)/(

#### Solve Using Reduced Row Echelon Form (SymPy solution only)

In [324]:
# the augmented matrix
A = sp.Matrix([[4, 3, 2, 25],
               [-2, 2, 3, -10],
               [3, -5, 2, -4]])
A

Matrix([
[ 4,  3, 2,  25],
[-2,  2, 3, -10],
[ 3, -5, 2,  -4]])

In [325]:
print(sp.latex(A))

\left[\begin{matrix}4 & 3 & 2 & 25\\-2 & 2 & 3 & -10\\3 & -5 & 2 & -4\end{matrix}\right]


$$
\left[\begin{matrix}4 & 3 & 2 & 25\\-2 & 2 & 3 & -10\\3 & -5 & 2 & -4\end{matrix}\right]
$$

In [326]:
A.rref(pivots=False)

Matrix([
[1, 0, 0,  5],
[0, 1, 0,  3],
[0, 0, 1, -2]])

#### Solve Using `sympy.linsolve()` (3 methods)

##### Method 1 - List of Equations Form

In [327]:
# note the change in sign of the values from
# the column matrix
system = [4 * x + 3 * y + 2 * z - 25,
          -2 * x + 2 * y + 3 * z + 10,
          3 * x - 5 * y + 2 * z + 4]
system

[4*x + 3*y + 2*z - 25, -2*x + 2*y + 3*z + 10, 3*x - 5*y + 2*z + 4]

In [328]:
system[0]

4*x + 3*y + 2*z - 25

In [329]:
sp.linsolve(system, (x, y, z))

{(5, 3, -2)}

##### Method 2 - Augmented Matrix Form

In [330]:
A

Matrix([
[ 4,  3, 2,  25],
[-2,  2, 3, -10],
[ 3, -5, 2,  -4]])

In [331]:
sp.linsolve(A, (x, y, z))

{(5, 3, -2)}

##### Method 3 - $A*x=b$ Form

In [332]:
A = sp_M
A

Matrix([
[ 4,  3, 2],
[-2,  2, 3],
[ 3, -5, 2]])

In [333]:
b = sp_K
b

Matrix([
[ 25],
[-10],
[ -4]])

In [334]:
sp.linsolve((A, b), x, y, z)

{(5, 3, -2)}

#### Solve Using `np.linalg.solve()`

In [335]:
M = np.array([[4, 3, 2],
              [-2, 2, 3],
              [3, -5, 2]])
M

array([[ 4,  3,  2],
       [-2,  2,  3],
       [ 3, -5,  2]])

In [336]:
K = np.array([[25],
              [-10],
              [-4]])
K

array([[ 25],
       [-10],
       [ -4]])

In [337]:
np.linalg.solve(M, K)

array([[ 5.],
       [ 3.],
       [-2.]])

## 1.2.1.4 Supplemental Reading - [Linear Algebra](https://patrickwalls.github.io/mathematicalpython/linear-algebra/linear-algebra-scipy/)

### Linear Algebra with SciPy

In [338]:
import scipy.linalg as la

#### Numpy Arrays: 1D, 2D and 3D

##### 1D

In [339]:
a = np.array([1, 3, -2, 1])
a

array([ 1,  3, -2,  1])

In [340]:
a.ndim, a.shape, a.size

(1, (4,), 4)

##### 2D

In [341]:
M = np.array([[1, 2],
              [3, 7],
              [-1, 5]])
M

array([[ 1,  2],
       [ 3,  7],
       [-1,  5]])

In [342]:
M.ndim, M.shape, M.size

(2, (3, 2), 6)

In [343]:
M_column = M[:, 1]
print(M_column)

[2 7 5]


In [344]:
M_column.ndim, M_column.shape, M_column.size

(1, (3,), 3)

In [345]:
M_column = M_column.reshape(3, 1)

In [346]:
M_column

array([[2],
       [7],
       [5]])

In [347]:
M_column.ndim, M_column.shape, M_column.size

(2, (3, 1), 3)

##### 3D

In [348]:
M = np.array([[[1, 2, 100],
               [3, 4, 100]],

              [[5, 6, 100],
               [7, 8, 100]],

              [[9, 10, 100],
               [11, 12, 100]],

              [[13, 14, 100],
               [15, 16, 100]]])
M

array([[[  1,   2, 100],
        [  3,   4, 100]],

       [[  5,   6, 100],
        [  7,   8, 100]],

       [[  9,  10, 100],
        [ 11,  12, 100]],

       [[ 13,  14, 100],
        [ 15,  16, 100]]])

In [349]:
M.ndim, M.shape, M.size

(3, (4, 2, 3), 24)

#### Matrix Operations and Functions

##### Arithmetic Operations

Arithmetic array operators: `+`, `-`, `/`, `*`, and `**` are performed elementwise on NumPy arrays

In [350]:
M = np.array([[3, 4],
              [-1, 5]])
M

array([[ 3,  4],
       [-1,  5]])

In [351]:
M + M

array([[ 6,  8],
       [-2, 10]])

In [352]:
M * M

array([[ 9, 16],
       [ 1, 25]])

In [353]:
M / M

array([[1., 1.],
       [1., 1.]])

In [354]:
M**3

array([[ 27,  64],
       [ -1, 125]])

##### Matrix Multiplication

In [355]:
M @ M

array([[ 5, 32],
       [-8, 21]])

In [356]:
M.dot(M)

array([[ 5, 32],
       [-8, 21]])

###### Example

Compute $2I + 3A - AB$ for

$A = \left[\begin{matrix}1 & 3\\-1 & 7\end{matrix}\right]$

$B = \left[\begin{matrix}5 & 2\\1 & 2\end{matrix}\right]$

In [357]:
A = np.array([[1, 3],
              [-1, 7]])
B = np.array([[5, 2],
              [1, 2]])
I = np.eye(2)

In [358]:
2 * I + 3 * A - A @ B

array([[-3.,  1.],
       [-5., 11.]])

##### Matrix Powers - `np.linalg.matrix_power()`

In [359]:
M

array([[ 3,  4],
       [-1,  5]])

In [360]:
np.linalg.matrix_power(M, 3)

array([[-17, 180],
       [-45,  73]])

In [361]:
M @ M @ M

array([[-17, 180],
       [-45,  73]])

In [362]:
M.dot(M).dot(M)

array([[-17, 180],
       [-45,  73]])

##### Transpose

In [363]:
M

array([[ 3,  4],
       [-1,  5]])

In [364]:
M.T

array([[ 3, -1],
       [ 4,  5]])

Notice that $MM^{T}$ is a symmetric matrix

In [365]:
M @ M.T

array([[25, 17],
       [17, 26]])

In [366]:
M.T @ M

array([[10,  7],
       [ 7, 41]])

In [367]:
a, b, c, d = sp.symbols('a b c c')

M = sp.Matrix([[a, b],
                [c, d]])

M

Matrix([
[a, b],
[c, c]])

In [368]:
M.T

Matrix([
[a, c],
[b, c]])

In [369]:
M @ M.T # symmetric

Matrix([
[a**2 + b**2, a*c + b*c],
[  a*c + b*c,    2*c**2]])

In [370]:
M.T @ M # symmetric

Matrix([
[a**2 + c**2,  a*b + c**2],
[ a*b + c**2, b**2 + c**2]])

##### Inverse

In [371]:
A = np.array([[1, 2],
              [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [372]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

##### Trace

In [373]:
A

array([[1, 2],
       [3, 4]])

In [374]:
np.trace(A)

5

In [375]:
M

Matrix([
[a, b],
[c, c]])

In [376]:
M.trace()

a + c

##### Determinant

In [377]:
# scipy
la.det(A)

-2.0

In [378]:
# numpy
np.linalg.det(A)

-2.0000000000000004

In [379]:
sp_A = sp.Matrix(A)
sp_A

Matrix([
[1, 2],
[3, 4]])

In [380]:
sp_A.det(), sp.det(sp_A)

(-2, -2)

In [381]:
M.det()

a*c - b*c

### Solving Linear Systems

#### Linear Systems

A **linear system of equations** is a collection of linear equations:

$
a_{00}x_{0} + a_{01}x_{1} + \dots + a_{0n}x_{n} = b_{0} \\
a_{10}x_{0} + a_{11}x_{1} + \dots + a_{1n}x_{n} = b_{1} \\
\vdots \\
a_{m0}x_{0} + a_{m1}x_{1} + \dots + a_{mn}x_{n} = b_{m}
$

In matrix notation, a linear system is $Ax = b$ where

$A =
\left[
\begin{matrix}
a_{00} & a_{01} & \dots & a_{0n} \\
a_{10} & a_{11} & \dots & a \\
\vdots & & & \vdots \\
a_{m0} & a_{m1} & \dots & a_{mn}
\end{matrix}
\right] ,
x =
\left[
\begin{matrix}
x_{0}  \\
x_{1}  \\
\vdots  \\
x_{n}  
\end{matrix}
\right] ,
b =
\left[
\begin{matrix}
b_{0}  \\
b_{1}  \\
\vdots  \\
b_{m}  
\end{matrix}
\right]
$

#### Gaussian Elimination

Perform elementary row operations to reduce the system to its row echelen form and then solve

###### Elementary Row Operations

1. Add $k$ times row $j$ to row $i$
2. Multiply row $i$ by scalar $k$
3. Switch rows $i$ and $j$

In [382]:
a, b, c, d, e, f, g, h, i, k = sp.symbols('a b c d e f g h i k')

A = sp.Matrix([[a, b, c],
               [d, e, f],
               [g, h, i]])

- Each of the **elementary row operations** is the result of matrix multiplication by an elementary matrix on the left.
- For example, $E_k$ is used to add 3 times row 2 to row 0

In [383]:
# add k times row 2 to row 0
Ek = sp.Matrix([[1, 0, k],
                [0, 1, 0],
                [0, 0, 1]])

In [384]:
Ek

Matrix([
[1, 0, k],
[0, 1, 0],
[0, 0, 1]])

In [385]:
A

Matrix([
[a, b, c],
[d, e, f],
[g, h, i]])

In [386]:
Ek @ A

Matrix([
[a + g*k, b + h*k, c + i*k],
[      d,       e,       f],
[      g,       h,       i]])

In [387]:
# multiply row 1 by -k
Ek = sp.Matrix([[1, 0, 0],
                [0, -k, 0],
                [0, 0, 1]])

In [388]:
Ek * A

Matrix([
[   a,    b,    c],
[-d*k, -e*k, -f*k],
[   g,    h,    i]])

In [389]:
# switch rows 1 and 2
Ek = sp.Matrix([[1, 0, 0],
                [0, 0, 1],
                [0, 1, 0]])

In [390]:
Ek * A

Matrix([
[a, b, c],
[g, h, i],
[d, e, f]])

###### Implementation

1. Add $k$ times row $j$ to row $i$
2. Multiply row $i$ by scalar $k$
3. Switch rows $i$ and $j$

###### $1.$ Add $k$ times row $j$ to row $i$

In [391]:
M = np.array([[1, 1],
              [3, 2]])
M

array([[1, 1],
       [3, 2]])

In [392]:
def add_row(A, k, i, j):
    'Add k times row j to row i in matrix A'
    n = A.shape[0]
    E = np.eye(n)
    if i == j:
        E[i, i] = k + 1
    else:
        E[i, j] = k
    return E @ A

In [393]:
add_row(M, 2, 0, 1)

array([[7., 5.],
       [3., 2.]])

In [394]:
add_row(M, 3, 1, 1)

array([[ 1.,  1.],
       [12.,  8.]])

###### $2.$ Multiply row $i$ by scalar $k$

In [395]:
def scale_row(A, k, i):
    'Multiply row i by k'
    n = A.shape[0]
    E = np.eye(n)
    E[i, i] = k
    return E @ A

In [396]:
M

array([[1, 1],
       [3, 2]])

In [397]:
scale_row(M, 3, 0)

array([[3., 3.],
       [3., 2.]])

In [398]:
scale_row(np.array([[3, 1], [-2, 7]]), 3, 1)

array([[ 3.,  1.],
       [-6., 21.]])

In [399]:
A = np.array([[1, 1, 1],
              [1, -1, 0]])

In [400]:
scale_row(A, 5, 1)

array([[ 1.,  1.,  1.],
       [ 5., -5.,  0.]])

###### $3.$ Switch rows $i$ and $j$

In [401]:
def switch_rows(A, i, j):
    'Switch rows i and j in matrix A'
    n = A.shape[0]
    E = np.eye(n)
    E[i, i] = 0
    E[j, j] = 0
    E[i, j] = 1
    E[j, i] = 1
    print(E)
    return E @ A

In [402]:
A = np.array([[1, 1, 1],
              [1, -1, 0]])
A

array([[ 1,  1,  1],
       [ 1, -1,  0]])

In [403]:
switch_rows(A, 0, 1)

[[0. 1.]
 [1. 0.]]


array([[ 1., -1.,  0.],
       [ 1.,  1.,  1.]])

## 1.2.1.5 Practice Quiz

### 1. Raise a square matrix A to the integer power of n

In [404]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [405]:
A @ A @ A

array([[ 468,  576,  684],
       [1062, 1305, 1548],
       [1656, 2034, 2412]])

In [406]:
np.linalg.matrix_power(A, 3)

array([[ 468,  576,  684],
       [1062, 1305, 1548],
       [1656, 2034, 2412]])

### 2. Compute eigenvalues for a squaqre matrix A.

In [407]:
np.linalg.eig(A)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

### 3. This line of code will multiply matrix A by a matrix B

In [408]:
np.dot(A, A)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### 4. In order to add two matrices, they do not need to have the same dimension.

Answer: false

### 5. Which line of code will allow you to solve a system of linear equations, where A is the coefficient matrix and B is the column matix, $(Av = B)$?

Answer: `np.linalg(A,B)`

### 6. Find the inverse of a matrix

In [409]:
M, np.linalg.inv(M)

(array([[1, 1],
        [3, 2]]),
 array([[-2.,  1.],
        [ 3., -1.]]))

In [410]:
np.linalg.inv(M) @ M

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])