<a href="https://colab.research.google.com/github/PaulToronto/Howard-University-Coursera-Linear-Algebra-For-Data-Science-Specialization/blob/main/1_2_1_Using_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.2.1 Using Linear Algebra

In [1]:
import numpy as np
import random
import sympy as sp
import matplotlib.pyplot as plt

## 1.2.1.1 Introduction to Linear Algebra Functions in Python

In [2]:
M = np.linspace(-8, 8, 9).reshape(3, 3)
N = np.random.randint(-8, 8, size=(3, 3))
O = 2*N

sp_M = sp.Matrix(M)
sp_N = sp.Matrix(N)
sp_O = sp.Matrix(O)

v1 = np.array([1, 3, 5, 7])
v2 = np.array([2, 4, 6, 8])
v3 = np.array([-2, 5, 1, 3])

sp_v1 = sp.Matrix(v1)
sp_v2 = sp.Matrix(v2)
sp_v3 = sp.Matrix(v3)

In [3]:
M, sp_M, N, sp_N, O, sp_O

(array([[-8., -6., -4.],
        [-2.,  0.,  2.],
        [ 4.,  6.,  8.]]),
 Matrix([
 [-8.0, -6.0, -4.0],
 [-2.0,    0,  2.0],
 [ 4.0,  6.0,  8.0]]),
 array([[-6, -7,  2],
        [-7,  6, -3],
        [ 3, -8,  2]]),
 Matrix([
 [-6, -7,  2],
 [-7,  6, -3],
 [ 3, -8,  2]]),
 array([[-12, -14,   4],
        [-14,  12,  -6],
        [  6, -16,   4]]),
 Matrix([
 [-12, -14,  4],
 [-14,  12, -6],
 [  6, -16,  4]]))

In [4]:
v1

array([1, 3, 5, 7])

In [5]:
sp_v1

Matrix([
[1],
[3],
[5],
[7]])

### `dot()` for two vectors

The `dot` function calculates the **dot product** of two vectors.

In [6]:
v1, v2

(array([1, 3, 5, 7]), array([2, 4, 6, 8]))

In [7]:
total = 0;
for i in range(4):
    total += v1[i] * v2[i]

total

100

In [8]:
sum([v1[i] * v2[i] for i in range(4)])

100

In [9]:
np.dot(v1, v2)

100

In [10]:
v1.dot(v2)

100

#### Sympy

In [11]:
sp.DotProduct(sp_v1, sp_v2)

DotProduct(Matrix([
[1],
[3],
[5],
[7]]), Matrix([
[2],
[4],
[6],
[8]]))

In [12]:
sp.DotProduct(sp_v1, sp_v2).simplify()

100

In [13]:
sp_v1.dot(sp_v2)

100

### `dot()` for two matrices

This is matrix multiplication

In [14]:
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [15]:
N

array([[-6, -7,  2],
       [-7,  6, -3],
       [ 3, -8,  2]])

In [16]:
N[0,:], N[1, :], N[2,:] # rows of N

(array([-6, -7,  2]), array([-7,  6, -3]), array([ 3, -8,  2]))

In [17]:
N[:,0], N[:,1], N[:,2] # columns of N

(array([-6, -7,  3]), array([-7,  6, -8]), array([ 2, -3,  2]))

In [18]:
np.dot(N, M)

array([[ 70.,  48.,  26.],
       [ 32.,  24.,  16.],
       [  0.,  -6., -12.]])

In [19]:
np.dot(M, N)

array([[ 78.,  52.,  -6.],
       [ 18.,  -2.,   0.],
       [-42., -56.,   6.]])

In [20]:
N_dot_M = np.zeros((3, 3))

for i in range(3):
    for j in range(3):
        row_N = N[i,:]
        col_M = M[:,j]
        N_dot_M[i,j] = np.dot(row_N, col_M)

N_dot_M

array([[ 70.,  48.,  26.],
       [ 32.,  24.,  16.],
       [  0.,  -6., -12.]])

In [21]:
N.dot(M)

array([[ 70.,  48.,  26.],
       [ 32.,  24.,  16.],
       [  0.,  -6., -12.]])

In [22]:
N

array([[-6, -7,  2],
       [-7,  6, -3],
       [ 3, -8,  2]])

In [23]:
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [24]:
np.matmul(N, M) # also the dot product

array([[ 70.,  48.,  26.],
       [ 32.,  24.,  16.],
       [  0.,  -6., -12.]])

In [25]:
N @ M # also the dot product

array([[ 70.,  48.,  26.],
       [ 32.,  24.,  16.],
       [  0.,  -6., -12.]])

In [26]:
N * M # element-wise mutliplication

array([[ 48.,  42.,  -8.],
       [ 14.,   0.,  -6.],
       [ 12., -48.,  16.]])

#### SymPy

In [27]:
N.dot(M)

array([[ 70.,  48.,  26.],
       [ 32.,  24.,  16.],
       [  0.,  -6., -12.]])

In [28]:
np.matmul(N, M)

array([[ 70.,  48.,  26.],
       [ 32.,  24.,  16.],
       [  0.,  -6., -12.]])

In [29]:
sp_N

Matrix([
[-6, -7,  2],
[-7,  6, -3],
[ 3, -8,  2]])

In [30]:
sp_M

Matrix([
[-8.0, -6.0, -4.0],
[-2.0,    0,  2.0],
[ 4.0,  6.0,  8.0]])

In [31]:
sp_N * sp_M

Matrix([
[70.0, 48.0,  26.0],
[32.0, 24.0,  16.0],
[   0, -6.0, -12.0]])

In [32]:
sp_N @ sp_M

Matrix([
[70.0, 48.0,  26.0],
[32.0, 24.0,  16.0],
[   0, -6.0, -12.0]])

In [33]:
sp.matrices.dense.matrix_multiply_elementwise(sp_N, sp_M)

Matrix([
[48.0,  42.0, -8.0],
[14.0,     0, -6.0],
[12.0, -48.0, 16.0]])

### `linalg.multi_dot()`

In [34]:
np.linalg.multi_dot([M, N, O])

array([[-1700.,  -372.,   -24.],
       [ -188.,  -276.,    84.],
       [ 1324.,  -180.,   192.]])

In [35]:
M.dot(N).dot(O)

array([[-1700.,  -372.,   -24.],
       [ -188.,  -276.,    84.],
       [ 1324.,  -180.,   192.]])

#### SymPy

In [36]:
sp_M * sp_N * sp_O

Matrix([
[-1700.0, -372.0, -24.0],
[ -188.0, -276.0,  84.0],
[ 1324.0, -180.0, 192.0]])

### `vdot()`

In [37]:
v1, v2

(array([1, 3, 5, 7]), array([2, 4, 6, 8]))

In [38]:
np.vdot(v1, v2), np.dot(v1, v2)

(100, 100)

#### SymPy

In [39]:
sp_v1.dot(sp_v2)

100

### `inner()`

Returns the inner product of two arrays

In [40]:
v3, v1

(array([-2,  5,  1,  3]), array([1, 3, 5, 7]))

In [41]:
np.inner(v3, v1)

39

In [42]:
np.dot(v3, v1)

39

#### SymPy

In [43]:
sp_v3.dot(sp_v1), sp_v1.dot(sp_v3)

(39, 39)

In [44]:
sp.DotProduct(sp_v3, sp_v1).simplify()

39

### `matmul()`

In [45]:
np.matmul(M, N)

array([[ 78.,  52.,  -6.],
       [ 18.,  -2.,   0.],
       [-42., -56.,   6.]])

In [46]:
np.dot(M, N)

array([[ 78.,  52.,  -6.],
       [ 18.,  -2.,   0.],
       [-42., -56.,   6.]])

#### SymPy

In [47]:
sp_M * sp_N

Matrix([
[ 78.0,  52.0, -6.0],
[ 18.0,  -2.0,    0],
[-42.0, -56.0,  6.0]])

In [48]:
sp_M @ sp_N

Matrix([
[ 78.0,  52.0, -6.0],
[ 18.0,  -2.0,    0],
[-42.0, -56.0,  6.0]])

In [49]:
M.dot(N)

array([[ 78.,  52.,  -6.],
       [ 18.,  -2.,   0.],
       [-42., -56.,   6.]])

### `linalg.matrix_power()`

In [50]:
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [51]:
np.linalg.matrix_power(M, 3)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [52]:
M.dot(M).dot(M)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [53]:
np.linalg.multi_dot([M, M, M])

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [54]:
np.matmul(np.matmul(M, M), M)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

#### SymPy

In [55]:
sp_M**3

Matrix([
[-576.0, -432.0, -288.0],
[-144.0,      0,  144.0],
[ 288.0,  432.0,  576.0]])

In [56]:
sp_M * sp_M * sp_M

Matrix([
[-576.0, -432.0, -288.0],
[-144.0,      0,  144.0],
[ 288.0,  432.0,  576.0]])

### `linalg.eig()`

Returns the eigenvalues and eigenvectors of a matrix

In [57]:
O

array([[-12, -14,   4],
       [-14,  12,  -6],
       [  6, -16,   4]])

In [58]:
eig_vals, eig_vects = np.linalg.eig(O)

In [59]:
eig_vals

array([ 24.38464885, -18.36612238,  -2.01852648])

In [60]:
eig_vects

array([[-0.3360547 ,  0.90131907, -0.07834466],
       [ 0.69030573,  0.4283102 ,  0.32512019],
       [-0.64073804,  0.06460882,  0.94242187]])

#### SymPy

In [61]:
sp_O.eigenvals()

{4/3 + 698/(9*(5137/54 + 17*sqrt(55227)*I/18)**(1/3)) + 2*(5137/54 + 17*sqrt(55227)*I/18)**(1/3): 1,
 4/3 + 698/(9*(-1/2 + sqrt(3)*I/2)*(5137/54 + 17*sqrt(55227)*I/18)**(1/3)) + 2*(-1/2 + sqrt(3)*I/2)*(5137/54 + 17*sqrt(55227)*I/18)**(1/3): 1,
 4/3 + 2*(-1/2 - sqrt(3)*I/2)*(5137/54 + 17*sqrt(55227)*I/18)**(1/3) + 698/(9*(-1/2 - sqrt(3)*I/2)*(5137/54 + 17*sqrt(55227)*I/18)**(1/3)): 1}

In [62]:
2, 10 - 2 * np.sqrt(5), 2 * np.sqrt(5) + 10

(2, 5.52786404500042, 14.47213595499958)

In [63]:
for eig_val in list(sp_O.eigenvals()):
    print(eig_val.evalf())

24.3846488540836 + 0.e-19*I
-18.3661223756974 + 0.e-22*I
-2.01852647838626 - 0.e-22*I


In [64]:
# takes too long to run
# eig_vects = sp_O.eigenvects()

### `linalg.eigh()`

Returns eigenvalues and eigenvectors of a complex Hermition matrix or a real symmetric matrix

In [65]:
eigh_vals, eigh_vects = np.linalg.eigh(N)

In [66]:
eigh_vals

array([-9.27143306, -3.59786152, 14.86929458])

In [67]:
eigh_vects

array([[ 0.88852885, -0.31311928, -0.33536965],
       [ 0.45112217,  0.46285964,  0.76305291],
       [ 0.0836975 ,  0.82928721, -0.55251919]])

### `linalg.det()`

Returns the determinant of a matrix

In [68]:
np.linalg.det(M), np.linalg.det(N), np.linalg.det(O)

(0.0, 113.00000000000003, 904.0000000000005)

#### SymPy

In [69]:
sp_M.det(), sp_N.det(), sp_O.det()

(0, 113, 904)

### `linalg.inv()`

Returns the inverse of a matrix

In [70]:
N

array([[-6, -7,  2],
       [-7,  6, -3],
       [ 3, -8,  2]])

In [71]:
np.linalg.inv(N)

array([[-0.10619469, -0.01769912,  0.07964602],
       [ 0.04424779, -0.15929204, -0.28318584],
       [ 0.33628319, -0.61061947, -0.75221239]])

In [72]:
np.matmul(N, np.linalg.inv(N))

array([[ 1.00000000e+00,  0.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [73]:
N.dot(np.linalg.inv(N))

array([[ 1.00000000e+00,  0.00000000e+00, -2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

#### SymPy

In [74]:
sp_N**-1

Matrix([
[-12/113,  -2/113,   9/113],
[  5/113, -18/113, -32/113],
[ 38/113, -69/113, -85/113]])

In [75]:
(sp_N**-1).evalf()

Matrix([
[-0.106194690265487, -0.0176991150442478,  0.079646017699115],
[0.0442477876106195,   -0.15929203539823, -0.283185840707965],
[ 0.336283185840708,  -0.610619469026549, -0.752212389380531]])

In [76]:
sp_N * sp_N**-1

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

## 1.2.1.2 Using Matrices in Python

### Building Matrices Using Numpy

In [77]:
L = np.linspace(0, 120, 25)
L

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100., 105.,
       110., 115., 120.])

In [78]:
M = L.reshape(5, 5)
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [79]:
R = np.random.randint(-5, 4, size=(4, 4))
R

array([[ 2, -4,  0, -4],
       [ 1, -3,  1, -4],
       [-2,  1, -2, -3],
       [-5,  2,  2, -2]])

### Building Matrices Using SymPy

In [80]:
sp.Matrix([[1, -1], [3, 4], [0, 2]])

Matrix([
[1, -1],
[3,  4],
[0,  2]])

In [81]:
sp_M = sp.Matrix(M)
sp_M

Matrix([
[    0,   5.0,  10.0,  15.0,  20.0],
[ 25.0,  30.0,  35.0,  40.0,  45.0],
[ 50.0,  55.0,  60.0,  65.0,  70.0],
[ 75.0,  80.0,  85.0,  90.0,  95.0],
[100.0, 105.0, 110.0, 115.0, 120.0]])

In [82]:
sp_R = sp.Matrix(R)
sp_R

Matrix([
[ 2, -4,  0, -4],
[ 1, -3,  1, -4],
[-2,  1, -2, -3],
[-5,  2,  2, -2]])

### Accessing Matrix Entries: NumPy and SymPy

In [83]:
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [84]:
# first row
M[0]

array([ 0.,  5., 10., 15., 20.])

In [85]:
M[0,:] # also first row

array([ 0.,  5., 10., 15., 20.])

In [86]:
# first rown
sp_M.row(0)

Matrix([[0, 5.0, 10.0, 15.0, 20.0]])

In [87]:
# also first row
sp_M[0, :]

Matrix([[0, 5.0, 10.0, 15.0, 20.0]])

In [88]:
# last row
M[-1]

array([100., 105., 110., 115., 120.])

In [89]:
# last row
sp_M.row(-1)

Matrix([[100.0, 105.0, 110.0, 115.0, 120.0]])

In [90]:
#first column
M[:,0]

array([  0.,  25.,  50.,  75., 100.])

In [91]:
sp_M.col(0)

Matrix([
[    0],
[ 25.0],
[ 50.0],
[ 75.0],
[100.0]])

In [92]:
# last column
M[:,-1]

array([ 20.,  45.,  70.,  95., 120.])

In [93]:
sp_M.col(-1)

Matrix([
[ 20.0],
[ 45.0],
[ 70.0],
[ 95.0],
[120.0]])

In [94]:
# first 3 rows
M[0:3]

array([[ 0.,  5., 10., 15., 20.],
       [25., 30., 35., 40., 45.],
       [50., 55., 60., 65., 70.]])

In [95]:
# first 3 rows
sp_M[0:3,:]

Matrix([
[   0,  5.0, 10.0, 15.0, 20.0],
[25.0, 30.0, 35.0, 40.0, 45.0],
[50.0, 55.0, 60.0, 65.0, 70.0]])

In [96]:
# third and fourth columns
M[:,2:4]

array([[ 10.,  15.],
       [ 35.,  40.],
       [ 60.,  65.],
       [ 85.,  90.],
       [110., 115.]])

In [97]:
sp_M[:, 2:4]

Matrix([
[ 10.0,  15.0],
[ 35.0,  40.0],
[ 60.0,  65.0],
[ 85.0,  90.0],
[110.0, 115.0]])

In [98]:
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [99]:
# first 3 rows, 2nd, 3rd and 4th columns
M[:3, 1:4]

array([[ 5., 10., 15.],
       [30., 35., 40.],
       [55., 60., 65.]])

In [100]:
sp_M[:3, 1:4]

Matrix([
[ 5.0, 10.0, 15.0],
[30.0, 35.0, 40.0],
[55.0, 60.0, 65.0]])

In [101]:
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [102]:
# first 3 rows, 2nd and 4th columns
M[:3, (1, 3)]

array([[ 5., 15.],
       [30., 40.],
       [55., 65.]])

In [103]:
sp_M[:3, (1, 3)]

Matrix([
[ 5.0, 15.0],
[30.0, 40.0],
[55.0, 65.0]])

In [104]:
# the entry at the intersection of
# the 2nd row and the 2nd column
M[1, 1]

30.0

In [105]:
sp_M[1,1]

30.0000000000000

## 1.2.1.3 Solving Linear Equations Using Python

### Example

$
\begin{align}
4x + 3y + 2x &= 25 \\
-2x + 2y + 3z &= -10 \\
3x - 5y + 2z &= -4
\end{align}
$

#### Solve Using the Inverse Method

In a nutshell, the solution is found by multiplying the inverse of the coefficent matrix, $M^{-1}$ by the column matrix, $K$.

Let $V$ be the solution, then

$V = M^{-1} * K$

Details about why this equation works are shown in this notebook.

In [106]:
# M is the coefficient matrix
M = np.array([[4, 3, 2],
              [-2, 2, 3],
              [3, -5, 2]])
M

array([[ 4,  3,  2],
       [-2,  2,  3],
       [ 3, -5,  2]])

In [107]:
# K is the column matrix
K = np.array([[25],
              [-10],
              [-4]])
K

array([[ 25],
       [-10],
       [ -4]])

In [108]:
V = np.array([['x'],
              ['y'],
              ['z']])
V

array([['x'],
       ['y'],
       ['z']], dtype='<U1')

The system of linear equations in this example can be written as:

$
M * V = K \\
\implies
M^{-1} * M * V = M^{-1} * K \\
\implies
I * V = M^{-1} * K \\
\implies
V = M^{-1} * K
$

In [109]:
np.linalg.inv(M).dot(K)

array([[ 5.],
       [ 3.],
       [-2.]])

##### Sympy

In [110]:
sp_M = sp.Matrix(M)
sp_M

Matrix([
[ 4,  3, 2],
[-2,  2, 3],
[ 3, -5, 2]])

In [111]:
sp_K = sp.Matrix(K)
sp_K

Matrix([
[ 25],
[-10],
[ -4]])

In [112]:
sp_M**-1 * sp_K

Matrix([
[ 5],
[ 3],
[-2]])

##### Symbolic summary of this method

In [113]:
x, y, z = sp.symbols('x y z')
m_11, m_12, m_13 = sp.symbols('m_11 m_12 m_13')
m_21, m_22, m_23 = sp.symbols('m_21 m_22 m_23')
m_31, m_32, m_33 = sp.symbols('m_31 m_32 m_33')
k_1, k_2, k_3 = sp.symbols('k_1 k_2 k_3')

In [114]:
V = sp.Matrix([[x], [y], [z]])
V

Matrix([
[x],
[y],
[z]])

In [115]:
M = sp.Matrix([[m_11, m_12, m_13],
               [m_21, m_22, m_23],
               [m_31, m_32, m_33]])
M

Matrix([
[m_11, m_12, m_13],
[m_21, m_22, m_23],
[m_31, m_32, m_33]])

In [116]:
K = sp.Matrix([[k_1], [k_2], [k_3]])
K

Matrix([
[k_1],
[k_2],
[k_3]])

In [117]:
sp.Eq(M * V, K)

Eq(Matrix([
[m_11*x + m_12*y + m_13*z],
[m_21*x + m_22*y + m_23*z],
[m_31*x + m_32*y + m_33*z]]), Matrix([
[k_1],
[k_2],
[k_3]]))

In [118]:
sp.Eq(V, M**-1 * K)

Eq(Matrix([
[x],
[y],
[z]]), Matrix([
[ k_1*(m_22*m_33 - m_23*m_32)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_2*(-m_12*m_33 + m_13*m_32)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_3*(m_12*m_23 - m_13*m_22)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31)],
[k_1*(-m_21*m_33 + m_23*m_31)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_2*(m_11*m_33 - m_13*m_31)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_3*(-m_11*m_23 + m_13*m_21)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31)],
[ k_1*(m_21*m_32 - m_22*m_31)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_2*(-m_11*m_32 + m_12*m_31)/(

#### Solve Using Reduced Row Echelon Form (SymPy solution only)

In [119]:
# the augmented matrix
A = sp.Matrix([[4, 3, 2, 25],
               [-2, 2, 3, -10],
               [3, -5, 2, -4]])
A

Matrix([
[ 4,  3, 2,  25],
[-2,  2, 3, -10],
[ 3, -5, 2,  -4]])

In [120]:
print(sp.latex(A))

\left[\begin{matrix}4 & 3 & 2 & 25\\-2 & 2 & 3 & -10\\3 & -5 & 2 & -4\end{matrix}\right]


$$
\left[\begin{matrix}4 & 3 & 2 & 25\\-2 & 2 & 3 & -10\\3 & -5 & 2 & -4\end{matrix}\right]
$$

In [121]:
A.rref(pivots=False)

Matrix([
[1, 0, 0,  5],
[0, 1, 0,  3],
[0, 0, 1, -2]])

#### Solve Using `sympy.linsolve()` (3 methods)

##### Method 1 - List of Equations Form

In [122]:
# note the change in sign of the values from
# the column matrix
system = [4 * x + 3 * y + 2 * z - 25,
          -2 * x + 2 * y + 3 * z + 10,
          3 * x - 5 * y + 2 * z + 4]
system

[4*x + 3*y + 2*z - 25, -2*x + 2*y + 3*z + 10, 3*x - 5*y + 2*z + 4]

In [123]:
system[0]

4*x + 3*y + 2*z - 25

In [124]:
sp.linsolve(system, (x, y, z))

{(5, 3, -2)}

##### Method 2 - Augmented Matrix Form

In [125]:
A

Matrix([
[ 4,  3, 2,  25],
[-2,  2, 3, -10],
[ 3, -5, 2,  -4]])

In [126]:
sp.linsolve(A, (x, y, z))

{(5, 3, -2)}

##### Method 3 - $A*x=b$ Form

In [127]:
A = sp_M
A

Matrix([
[ 4,  3, 2],
[-2,  2, 3],
[ 3, -5, 2]])

In [128]:
b = sp_K
b

Matrix([
[ 25],
[-10],
[ -4]])

In [129]:
sp.linsolve((A, b), x, y, z)

{(5, 3, -2)}

#### Solve Using `np.linalg.solve()`

In [130]:
M = np.array([[4, 3, 2],
              [-2, 2, 3],
              [3, -5, 2]])
M

array([[ 4,  3,  2],
       [-2,  2,  3],
       [ 3, -5,  2]])

In [131]:
K = np.array([[25],
              [-10],
              [-4]])
K

array([[ 25],
       [-10],
       [ -4]])

In [132]:
np.linalg.solve(M, K)

array([[ 5.],
       [ 3.],
       [-2.]])

## 1.2.1.4 Supplemental Reading - [Linear Algebra](https://patrickwalls.github.io/mathematicalpython/linear-algebra/linear-algebra-scipy/)

### Linear Algebra with SciPy

In [133]:
import scipy.linalg as la

#### Numpy Arrays: 1D, 2D and 3D

##### 1D

In [134]:
a = np.array([1, 3, -2, 1])
a

array([ 1,  3, -2,  1])

In [135]:
a.ndim, a.shape, a.size

(1, (4,), 4)

##### 2D

In [136]:
M = np.array([[1, 2],
              [3, 7],
              [-1, 5]])
M

array([[ 1,  2],
       [ 3,  7],
       [-1,  5]])

In [137]:
M.ndim, M.shape, M.size

(2, (3, 2), 6)

In [138]:
M_column = M[:, 1]
print(M_column)

[2 7 5]


In [139]:
M_column.ndim, M_column.shape, M_column.size

(1, (3,), 3)

In [140]:
M_column = M_column.reshape(3, 1)

In [141]:
M_column

array([[2],
       [7],
       [5]])

In [142]:
M_column.ndim, M_column.shape, M_column.size

(2, (3, 1), 3)

##### 3D

In [143]:
M = np.array([[[1, 2, 100],
               [3, 4, 100]],

              [[5, 6, 100],
               [7, 8, 100]],

              [[9, 10, 100],
               [11, 12, 100]],

              [[13, 14, 100],
               [15, 16, 100]]])
M

array([[[  1,   2, 100],
        [  3,   4, 100]],

       [[  5,   6, 100],
        [  7,   8, 100]],

       [[  9,  10, 100],
        [ 11,  12, 100]],

       [[ 13,  14, 100],
        [ 15,  16, 100]]])

In [144]:
M.ndim, M.shape, M.size

(3, (4, 2, 3), 24)

#### Matrix Operations and Functions

##### Arithmetic Operations

Arithmetic array operators: `+`, `-`, `/`, `*`, and `**` are performed elementwise on NumPy arrays

In [145]:
M = np.array([[3, 4],
              [-1, 5]])
M

array([[ 3,  4],
       [-1,  5]])

In [146]:
M + M

array([[ 6,  8],
       [-2, 10]])

In [147]:
M * M

array([[ 9, 16],
       [ 1, 25]])

In [148]:
M / M

array([[1., 1.],
       [1., 1.]])

In [149]:
M**3

array([[ 27,  64],
       [ -1, 125]])

##### Matrix Multiplication

In [150]:
M @ M

array([[ 5, 32],
       [-8, 21]])

In [151]:
M.dot(M)

array([[ 5, 32],
       [-8, 21]])

###### Example

Compute $2I + 3A - AB$ for

$A = \left[\begin{matrix}1 & 3\\-1 & 7\end{matrix}\right]$

$B = \left[\begin{matrix}5 & 2\\1 & 2\end{matrix}\right]$

In [152]:
A = np.array([[1, 3],
              [-1, 7]])
B = np.array([[5, 2],
              [1, 2]])
I = np.eye(2)

In [153]:
2 * I + 3 * A - A @ B

array([[-3.,  1.],
       [-5., 11.]])

##### Matrix Powers - `np.linalg.matrix_power()`

In [154]:
M

array([[ 3,  4],
       [-1,  5]])

In [155]:
np.linalg.matrix_power(M, 3)

array([[-17, 180],
       [-45,  73]])

In [156]:
M @ M @ M

array([[-17, 180],
       [-45,  73]])

In [157]:
M.dot(M).dot(M)

array([[-17, 180],
       [-45,  73]])

##### Transpose

In [158]:
M

array([[ 3,  4],
       [-1,  5]])

In [159]:
M.T

array([[ 3, -1],
       [ 4,  5]])

Notice that $MM^{T}$ is a symmetric matrix

In [160]:
M @ M.T

array([[25, 17],
       [17, 26]])

In [161]:
M.T @ M

array([[10,  7],
       [ 7, 41]])

In [162]:
a, b, c, d = sp.symbols('a b c c')

M = sp.Matrix([[a, b],
                [c, d]])

M

Matrix([
[a, b],
[c, c]])

In [163]:
M.T

Matrix([
[a, c],
[b, c]])

In [164]:
M @ M.T # symmetric

Matrix([
[a**2 + b**2, a*c + b*c],
[  a*c + b*c,    2*c**2]])

In [165]:
M.T @ M # symmetric

Matrix([
[a**2 + c**2,  a*b + c**2],
[ a*b + c**2, b**2 + c**2]])

##### Inverse

In [166]:
A = np.array([[1, 2],
              [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [167]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

##### Trace

In [168]:
A

array([[1, 2],
       [3, 4]])

In [169]:
np.trace(A)

5

In [170]:
M

Matrix([
[a, b],
[c, c]])

In [171]:
M.trace()

a + c

##### Determinant

In [172]:
# scipy
la.det(A)

-2.0

In [173]:
# numpy
np.linalg.det(A)

-2.0000000000000004

In [174]:
sp_A = sp.Matrix(A)
sp_A

Matrix([
[1, 2],
[3, 4]])

In [175]:
sp_A.det(), sp.det(sp_A)

(-2, -2)

In [176]:
M.det()

a*c - b*c

### Solving Linear Systems

#### Linear Systems

A **linear system of equations** is a collection of linear equations:

$
a_{00}x_{0} + a_{01}x_{1} + \dots + a_{0n}x_{n} = b_{0} \\
a_{10}x_{0} + a_{11}x_{1} + \dots + a_{1n}x_{n} = b_{1} \\
\vdots \\
a_{m0}x_{0} + a_{m1}x_{1} + \dots + a_{mn}x_{n} = b_{m}
$

In matrix notation, a linear system is $Ax = b$ where

$A =
\left[
\begin{matrix}
a_{00} & a_{01} & \dots & a_{0n} \\
a_{10} & a_{11} & \dots & a \\
\vdots & & & \vdots \\
a_{m0} & a_{m1} & \dots & a_{mn}
\end{matrix}
\right] ,
x =
\left[
\begin{matrix}
x_{0}  \\
x_{1}  \\
\vdots  \\
x_{n}  
\end{matrix}
\right] ,
b =
\left[
\begin{matrix}
b_{0}  \\
b_{1}  \\
\vdots  \\
b_{m}  
\end{matrix}
\right]
$

#### Gaussian Elimination

Perform elementary row operations to reduce the system to its row echelen form and then solve

###### Elementary Row Operations

1. Add $k$ times row $j$ to row $i$
2. Multiply row $i$ by scalar $k$
3. Switch rows $i$ and $j$

In [177]:
a, b, c, d, e, f, g, h, i, k = sp.symbols('a b c d e f g h i k')

A = sp.Matrix([[a, b, c],
               [d, e, f],
               [g, h, i]])

- Each of the **elementary row operations** is the result of matrix multiplication by an elementary matrix on the left.
- For example, $E_k$ is used to add 3 times row 2 to row 0

In [178]:
# add k times row 2 to row 0
Ek = sp.Matrix([[1, 0, k],
                [0, 1, 0],
                [0, 0, 1]])

In [179]:
Ek

Matrix([
[1, 0, k],
[0, 1, 0],
[0, 0, 1]])

In [180]:
A

Matrix([
[a, b, c],
[d, e, f],
[g, h, i]])

In [181]:
Ek @ A

Matrix([
[a + g*k, b + h*k, c + i*k],
[      d,       e,       f],
[      g,       h,       i]])

In [182]:
# multiply row 1 by -k
Ek = sp.Matrix([[1, 0, 0],
                [0, -k, 0],
                [0, 0, 1]])

In [183]:
Ek * A

Matrix([
[   a,    b,    c],
[-d*k, -e*k, -f*k],
[   g,    h,    i]])

In [184]:
# switch rows 1 and 2
Ek = sp.Matrix([[1, 0, 0],
                [0, 0, 1],
                [0, 1, 0]])

In [185]:
Ek * A

Matrix([
[a, b, c],
[g, h, i],
[d, e, f]])

###### Implementation

1. Add $k$ times row $j$ to row $i$
2. Multiply row $i$ by scalar $k$
3. Switch rows $i$ and $j$

###### $1.$ Add $k$ times row $j$ to row $i$

In [186]:
M = np.array([[1, 1],
              [3, 2]])
M

array([[1, 1],
       [3, 2]])

In [187]:
def add_row(A, k, i, j):
    'Add k times row j to row i in matrix A'
    n = A.shape[0]
    E = np.eye(n)
    if i == j:
        E[i, i] = k + 1
    else:
        E[i, j] = k
    return E @ A

In [188]:
add_row(M, 2, 0, 1)

array([[7., 5.],
       [3., 2.]])

In [189]:
add_row(M, 3, 1, 1)

array([[ 1.,  1.],
       [12.,  8.]])

###### $2.$ Multiply row $i$ by scalar $k$

In [190]:
def scale_row(A, k, i):
    'Multiply row i by k'
    n = A.shape[0]
    E = np.eye(n)
    E[i, i] = k
    return E @ A

In [191]:
M

array([[1, 1],
       [3, 2]])

In [192]:
scale_row(M, 3, 0)

array([[3., 3.],
       [3., 2.]])

In [193]:
scale_row(np.array([[3, 1], [-2, 7]]), 3, 1)

array([[ 3.,  1.],
       [-6., 21.]])

In [194]:
A = np.array([[1, 1, 1],
              [1, -1, 0]])

In [195]:
scale_row(A, 5, 1)

array([[ 1.,  1.,  1.],
       [ 5., -5.,  0.]])

###### $3.$ Switch rows $i$ and $j$

In [196]:
def switch_rows(A, i, j):
    'Switch rows i and j in matrix A'
    n = A.shape[0]
    E = np.eye(n)
    E[i, i] = 0
    E[j, j] = 0
    E[i, j] = 1
    E[j, i] = 1
    print(E)
    return E @ A

In [197]:
A = np.array([[1, 1, 1],
              [1, -1, 0]])
A

array([[ 1,  1,  1],
       [ 1, -1,  0]])

In [198]:
switch_rows(A, 0, 1)

[[0. 1.]
 [1. 0.]]


array([[ 1., -1.,  0.],
       [ 1.,  1.,  1.]])

## 1.2.1.5 Practice Quiz

### 1. Raise a square matrix A to the integer power of n

In [199]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [200]:
A @ A @ A

array([[ 468,  576,  684],
       [1062, 1305, 1548],
       [1656, 2034, 2412]])

In [201]:
np.linalg.matrix_power(A, 3)

array([[ 468,  576,  684],
       [1062, 1305, 1548],
       [1656, 2034, 2412]])

### 2. Compute eigenvalues for a squaqre matrix A.

In [202]:
np.linalg.eig(A)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

### 3. This line of code will multiply matrix A by a matrix B

In [203]:
np.dot(A, A)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### 4. In order to add two matrices, they do not need to have the same dimension.

Answer: false

### 5. Which line of code will allow you to solve a system of linear equations, where A is the coefficient matrix and B is the column matix, $(Av = B)$?

Answer: `np.linalg(A,B)`

### 6. Find the inverse of a matrix

In [204]:
M, np.linalg.inv(M)

(array([[1, 1],
        [3, 2]]),
 array([[-2.,  1.],
        [ 3., -1.]]))

In [205]:
np.linalg.inv(M) @ M

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])