<a href="https://colab.research.google.com/github/PaulToronto/Howard-University-Coursera-Linear_Algebra-For-Data-Science-Specialization/blob/main/1_2_1_Using_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.2.1 Using Linear Algebra

In [1]:
import numpy as np
import random
import sympy as sp
import matplotlib.pyplot as plt

## 1.2.1.1 Introduction to Linear Algebra Functions in Python

In [2]:
M = np.linspace(-8, 8, 9).reshape(3, 3)
N = np.random.randint(-8, 8, size=(3, 3))
O = 2*N

sp_M = sp.Matrix(M)
sp_N = sp.Matrix(N)
sp_O = sp.Matrix(O)

v1 = np.array([1, 3, 5, 7])
v2 = np.array([2, 4, 6, 8])
v3 = np.array([-2, 5, 1, 3])

sp_v1 = sp.Matrix(v1)
sp_v2 = sp.Matrix(v2)
sp_v3 = sp.Matrix(v3)

### `dot()` for two vectors

The `dot` function calculates the **dot product* of two vectors.

In [3]:
v1, v2

(array([1, 3, 5, 7]), array([2, 4, 6, 8]))

In [4]:
np.dot(v1, v2)

100

In [5]:
v1.dot(v2)

100

#### Sympy

In [6]:
sp.DotProduct(sp_v1, sp_v2)

DotProduct(Matrix([
[1],
[3],
[5],
[7]]), Matrix([
[2],
[4],
[6],
[8]]))

In [7]:
sp.DotProduct(sp_v1, sp_v2).simplify()

100

In [8]:
sp_v1.dot(sp_v2)

100

### `dot()` for two matrices

This is matrix multiplication

In [9]:
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [10]:
N

array([[ 4,  7,  4],
       [ 7,  2, -5],
       [ 0,  5,  0]])

In [11]:
np.dot(N, M)

array([[-30.,   0.,  30.],
       [-80., -72., -64.],
       [-10.,   0.,  10.]])

In [12]:
N.dot(M)

array([[-30.,   0.,  30.],
       [-80., -72., -64.],
       [-10.,   0.,  10.]])

In [13]:
np.matmul(N, M)

array([[-30.,   0.,  30.],
       [-80., -72., -64.],
       [-10.,   0.,  10.]])

#### SymPy

In [14]:
sp_N * sp_M

Matrix([
[-30.0,     0,  30.0],
[-80.0, -72.0, -64.0],
[-10.0,     0,  10.0]])

### `linalg.multi_dot()`

In [15]:
np.linalg.multi_dot([M, N, O])

array([[-1824., -1408.,   288.],
       [ -120.,  -208.,   -24.],
       [ 1584.,   992.,  -336.]])

#### SymPy

In [16]:
sp_M * sp_N * sp_O

Matrix([
[-1824.0, -1408.0,  288.0],
[ -120.0,  -208.0,  -24.0],
[ 1584.0,   992.0, -336.0]])

### `vdot()`

In [17]:
np.vdot(v1, v2)

100

#### SymPy

In [18]:
sp_v1.dot(sp_v2)

100

### `inner()`

Returns the inner product of two arrays

In [19]:
v3, v1

(array([-2,  5,  1,  3]), array([1, 3, 5, 7]))

In [20]:
np.inner(v3, v1)

39

In [21]:
np.dot(v3, v1)

39

#### SymPy

In [22]:
sp_v3.dot(sp_v1)

39

### `matmul()`

In [23]:
np.matmul(M, N)

array([[-74., -88.,  -2.],
       [ -8.,  -4.,  -8.],
       [ 58.,  80., -14.]])

In [24]:
np.dot(M, N)

array([[-74., -88.,  -2.],
       [ -8.,  -4.,  -8.],
       [ 58.,  80., -14.]])

#### SymPy

In [25]:
sp_M * sp_N

Matrix([
[-74.0, -88.0,  -2.0],
[ -8.0,  -4.0,  -8.0],
[ 58.0,  80.0, -14.0]])

### `linalg.matrix_power()`

In [26]:
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [27]:
np.linalg.matrix_power(M, 3)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [28]:
M.dot(M).dot(M)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [29]:
np.linalg.multi_dot([M, M, M])

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

In [30]:
np.matmul(np.matmul(M, M), M)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

#### SymPy

In [31]:
sp_M**3

Matrix([
[-576.0, -432.0, -288.0],
[-144.0,      0,  144.0],
[ 288.0,  432.0,  576.0]])

In [32]:
sp_M * sp_M * sp_M

Matrix([
[-576.0, -432.0, -288.0],
[-144.0,      0,  144.0],
[ 288.0,  432.0,  576.0]])

### `linalg.eig()`

Returns the eigenvalues and eigenvectors of a matrix

In [33]:
eig_vals, eig_vects = np.linalg.eig(O)

In [34]:
eig_vals

array([20.+0.j        , -4.+8.94427191j, -4.-8.94427191j])

In [35]:
eig_vects

array([[-0.80178373+0.j        ,  0.22664461-0.46780871j,
         0.22664461+0.46780871j],
       [-0.53452248+0.j        , -0.24407882+0.54577682j,
        -0.24407882-0.54577682j],
       [-0.26726124+0.j        ,  0.61019704+0.j        ,
         0.61019704-0.j        ]])

#### SymPy

In [36]:
sp_O.eigenvals()

{20: 1, -4 - 4*sqrt(5)*I: 1, -4 + 4*sqrt(5)*I: 1}

In [37]:
for eig_val in list(sp_O.eigenvals()):
    print(eig_val.evalf())

20.0000000000000
-4.0 - 8.94427190999916*I
-4.0 + 8.94427190999916*I


In [38]:
# takes too long to run
# eig_vects = sp_O.eigenvects()

### `linalg.eigh()`

Returns eigenvalues and eigenvectors of a complex Hermition matix or a real symmetric matrix

In [39]:
eigh_vals, eigh_vects = np.linalg.eigh(N)

In [40]:
eigh_vals

array([-6.50629901,  1.38158325, 11.12471577])

In [41]:
eigh_vects

array([[ 0.4671123 ,  0.58001292, -0.66737629],
       [-0.70108879, -0.21695936, -0.67926662],
       [ 0.53877695, -0.78518383, -0.30529617]])

### `linalg.det()`

Returns the determinant of a matrix

In [42]:
np.linalg.det(M), np.linalg.det(N), np.linalg.det(O)

(0.0, 239.99999999999997, 1919.9999999999986)

#### SymPy

In [43]:
sp_M.det(), sp_N.det(), sp_O.det()

(0, 240, 1920)

### `linalg.inv()`

Returns the inverse of a matrix

In [44]:
N

array([[ 4,  7,  4],
       [ 7,  2, -5],
       [ 0,  5,  0]])

In [45]:
np.linalg.inv(N)

array([[ 0.10416667,  0.08333333, -0.17916667],
       [ 0.        ,  0.        ,  0.2       ],
       [ 0.14583333, -0.08333333, -0.17083333]])

In [46]:
np.matmul(N, np.linalg.inv(N))

array([[ 1.00000000e+00,  0.00000000e+00, -3.33066907e-16],
       [ 2.77555756e-17,  1.00000000e+00, -1.38777878e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [47]:
N.dot(np.linalg.inv(N))

array([[ 1.00000000e+00,  0.00000000e+00, -3.33066907e-16],
       [ 2.77555756e-17,  1.00000000e+00, -1.38777878e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

#### SymPy

In [48]:
sp_N**-1

Matrix([
[5/48,  1/12, -43/240],
[   0,     0,     1/5],
[7/48, -1/12, -41/240]])

In [49]:
(sp_N**-1).evalf()

Matrix([
[0.104166666666667,  0.0833333333333333, -0.179166666666667],
[                0,                   0,                0.2],
[0.145833333333333, -0.0833333333333333, -0.170833333333333]])

In [50]:
sp_N * sp_N**-1

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

## 1.2.1.2 Using Matrices in Python

### Building Matrices Using Numpy

In [51]:
L = np.linspace(0, 120, 25)
L

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100., 105.,
       110., 115., 120.])

In [52]:
M = L.reshape(5, 5)
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [53]:
R = np.random.randint(-5, 4, size=(4, 4))
R

array([[ 2, -4, -4,  3],
       [-1, -4,  2, -3],
       [-4, -5,  0, -1],
       [-4, -1, -2, -3]])

### Building Matrices Using SymPy

In [54]:
sp_M = sp.Matrix(M)
sp_M

Matrix([
[  0.0,   5.0,  10.0,  15.0,  20.0],
[ 25.0,  30.0,  35.0,  40.0,  45.0],
[ 50.0,  55.0,  60.0,  65.0,  70.0],
[ 75.0,  80.0,  85.0,  90.0,  95.0],
[100.0, 105.0, 110.0, 115.0, 120.0]])

In [55]:
sp_R = sp.Matrix(R)
sp_R

Matrix([
[ 2, -4, -4,  3],
[-1, -4,  2, -3],
[-4, -5,  0, -1],
[-4, -1, -2, -3]])

### Accessing Matrix Entries: NumPy and SymPy

In [56]:
# first row
M[0]

array([ 0.,  5., 10., 15., 20.])

In [57]:
sp_M.row(1)

Matrix([[25.0, 30.0, 35.0, 40.0, 45.0]])

In [58]:
sp_M[1, :]

Matrix([[25.0, 30.0, 35.0, 40.0, 45.0]])

In [59]:
# last row
M[-1]

array([100., 105., 110., 115., 120.])

In [60]:
sp_M.row(-1)

Matrix([[100.0, 105.0, 110.0, 115.0, 120.0]])

In [61]:
#first column
M[:,0]

array([  0.,  25.,  50.,  75., 100.])

In [62]:
sp_M.col(0)

Matrix([
[  0.0],
[ 25.0],
[ 50.0],
[ 75.0],
[100.0]])

In [63]:
# last column
M[:,-1]

array([ 20.,  45.,  70.,  95., 120.])

In [64]:
sp_M.col(-1)

Matrix([
[ 20.0],
[ 45.0],
[ 70.0],
[ 95.0],
[120.0]])

In [65]:
# first 3 rows
M[0:3]

array([[ 0.,  5., 10., 15., 20.],
       [25., 30., 35., 40., 45.],
       [50., 55., 60., 65., 70.]])

In [66]:
sp_M[0:3,:]

Matrix([
[ 0.0,  5.0, 10.0, 15.0, 20.0],
[25.0, 30.0, 35.0, 40.0, 45.0],
[50.0, 55.0, 60.0, 65.0, 70.0]])

In [67]:
# second and third columns
M[:,2:4]

array([[ 10.,  15.],
       [ 35.,  40.],
       [ 60.,  65.],
       [ 85.,  90.],
       [110., 115.]])

In [68]:
sp_M[:, 2:4]

Matrix([
[ 10.0,  15.0],
[ 35.0,  40.0],
[ 60.0,  65.0],
[ 85.0,  90.0],
[110.0, 115.0]])

In [69]:
# first 3 rows, 2nd, 3rd and 4th columns
M[:3, 1:4]

array([[ 5., 10., 15.],
       [30., 35., 40.],
       [55., 60., 65.]])

In [70]:
sp_M[:3, 1:4]

Matrix([
[ 5.0, 10.0, 15.0],
[30.0, 35.0, 40.0],
[55.0, 60.0, 65.0]])

In [71]:
# first 3 rows, 2nd and 4th columns
M[:3, (1, 3)]

array([[ 5., 15.],
       [30., 40.],
       [55., 65.]])

In [72]:
sp_M[:3, (1, 3)]

Matrix([
[ 5.0, 15.0],
[30.0, 40.0],
[55.0, 65.0]])

In [73]:
# the entry at the intersection of 
# the 2nd row and the 2nd column
M[1, 1]

30.0

In [74]:
sp_M[1,1]

30.0000000000000

## 1.2.1.3 Solving Linear Equations Using Python

### Example

$
\begin{align}
4x + 3y + 2z &= 25 \\
-2x + 2y + 3z &= -10 \\
3x - 5y + 2z &= -4
\end{align}
$

#### Solve Using the Inverse Method

In a nutshell, the solution is found by multiplying the inverse of the coefficent matrix, $M^{-1}$ by the column matrix, $K$.

Let $V$ be the solution, then

$V = M^{-1} * K$

Details about why this equation works are shown in this notebook. 

In [75]:
# M is the coefficient matrix
M = np.array([[4, 3, 2],
              [-2, 2, 3],
              [3, -5, 2]])
M

array([[ 4,  3,  2],
       [-2,  2,  3],
       [ 3, -5,  2]])

In [76]:
# K is the column matrix
K = np.array([[25],
              [-10],
              [-4]])
K

array([[ 25],
       [-10],
       [ -4]])

In [77]:
V = np.array([['x'],
              ['y'],
              ['z']])
V

array([['x'],
       ['y'],
       ['z']], dtype='<U1')

The system of linear equations in this example can be written as:

$
M * V = K \\
\implies 
M^{-1} * M * V = M^{-1} * K \\
\implies
I * V = M^{-1} * K \\
\implies
V = M^{-1} * K
$

In [78]:
np.linalg.inv(M).dot(K)

array([[ 5.],
       [ 3.],
       [-2.]])

##### Sympy

In [79]:
sp_M = sp.Matrix(M)
sp_M

Matrix([
[ 4,  3, 2],
[-2,  2, 3],
[ 3, -5, 2]])

In [80]:
sp_K = sp.Matrix(K)
sp_K

Matrix([
[ 25],
[-10],
[ -4]])

In [81]:
sp_M**-1 * sp_K

Matrix([
[ 5],
[ 3],
[-2]])

##### Symbolic summary of this method

In [82]:
x, y, z = sp.symbols('x y z')
m_11, m_12, m_13 = sp.symbols('m_11 m_12 m_13')
m_21, m_22, m_23 = sp.symbols('m_21 m_22 m_23')
m_31, m_32, m_33 = sp.symbols('m_31 m_32 m_33')
k_1, k_2, k_3 = sp.symbols('k_1 k_2 k_3')

In [83]:
V = sp.Matrix([[x], [y], [z]])
V

Matrix([
[x],
[y],
[z]])

In [84]:
M = sp.Matrix([[m_11, m_12, m_13],
               [m_21, m_22, m_23],
               [m_31, m_32, m_33]])
M

Matrix([
[m_11, m_12, m_13],
[m_21, m_22, m_23],
[m_31, m_32, m_33]])

In [85]:
K = sp.Matrix([[k_1], [k_2], [k_3]])
K

Matrix([
[k_1],
[k_2],
[k_3]])

In [86]:
sp.Eq(M * V, K)

Eq(Matrix([
[m_11*x + m_12*y + m_13*z],
[m_21*x + m_22*y + m_23*z],
[m_31*x + m_32*y + m_33*z]]), Matrix([
[k_1],
[k_2],
[k_3]]))

In [87]:
sp.Eq(V, M**-1 * K)

Eq(Matrix([
[x],
[y],
[z]]), Matrix([
[ k_1*(m_22*m_33 - m_23*m_32)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_2*(-m_12*m_33 + m_13*m_32)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_3*(m_12*m_23 - m_13*m_22)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31)],
[k_1*(-m_21*m_33 + m_23*m_31)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_2*(m_11*m_33 - m_13*m_31)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_3*(-m_11*m_23 + m_13*m_21)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31)],
[ k_1*(m_21*m_32 - m_22*m_31)/(m_11*m_22*m_33 - m_11*m_23*m_32 - m_12*m_21*m_33 + m_12*m_23*m_31 + m_13*m_21*m_32 - m_13*m_22*m_31) + k_2*(-m_11*m_32 + m_12*m_31)/(

#### Solve Using Reduced Row Echelon Form (SymPy solution only)

In [88]:
# the augmented matrix
A = sp.Matrix([[4, 3, 2, 25],
               [-2, 2, 3, -10],
               [3, -5, 2, -4]])
A

Matrix([
[ 4,  3, 2,  25],
[-2,  2, 3, -10],
[ 3, -5, 2,  -4]])

In [89]:
A.rref(pivots=False)

Matrix([
[1, 0, 0,  5],
[0, 1, 0,  3],
[0, 0, 1, -2]])

#### Solve Using `sympy.linsolve()` (3 methods)

##### Method 1 - List of Equations Form

In [90]:
# note the change in sign of the values from 
# the column matrix
system = [4 * x + 3 * y + 2 * z - 25,
          -2 * x + 2 * y + 3 * z + 10,
          3 * x - 5 * y + 2 * z + 4]
system

[4*x + 3*y + 2*z - 25, -2*x + 2*y + 3*z + 10, 3*x - 5*y + 2*z + 4]

In [91]:
sp.linsolve(system, (x, y, z))

FiniteSet((5, 3, -2))

##### Method 2 - Augmented Matrix Form

In [92]:
A

Matrix([
[ 4,  3, 2,  25],
[-2,  2, 3, -10],
[ 3, -5, 2,  -4]])

In [93]:
sp.linsolve(A, (x, y, z))

FiniteSet((5, 3, -2))

##### Method 3 - $A*x=b$ Form

In [94]:
A = sp_M
A

Matrix([
[ 4,  3, 2],
[-2,  2, 3],
[ 3, -5, 2]])

In [95]:
b = sp_K
b

Matrix([
[ 25],
[-10],
[ -4]])

In [96]:
sp.linsolve((A, b), x, y, z)

FiniteSet((5, 3, -2))

#### Solve Using `np.linalg.solve()`

In [97]:
M = np.array([[4, 3, 2],
              [-2, 2, 3],
              [3, -5, 2]])
M

array([[ 4,  3,  2],
       [-2,  2,  3],
       [ 3, -5,  2]])

In [98]:
K = np.array([[25],
              [-10],
              [-4]])
K

array([[ 25],
       [-10],
       [ -4]])

In [99]:
np.linalg.solve(M, K)

array([[ 5.],
       [ 3.],
       [-2.]])

## 1.2.1.4 Supplemental Reading - [Linear Algebra](https://patrickwalls.github.io/mathematicalpython/linear-algebra/linear-algebra-scipy/)

### Linear Algebra with SciPy

In [100]:
import scipy.linalg as la

#### Numpy Arrays: 1D, 2D and 3D

##### 1D

In [101]:
a = np.array([1, 3, -2, 1])
a

array([ 1,  3, -2,  1])

In [102]:
a.ndim, a.shape, a.size

(1, (4,), 4)

##### 2D

In [103]:
M = np.array([[1, 2],
              [3, 7],
              [-1, 5]])
M

array([[ 1,  2],
       [ 3,  7],
       [-1,  5]])

In [104]:
M.ndim, M.shape, M.size

(2, (3, 2), 6)

In [105]:
M_column = M[:, 1]
print(M_column)

[2 7 5]


In [106]:
M_column.ndim, M_column.shape, M_column.size

(1, (3,), 3)

In [107]:
M_column = M_column.reshape(3, 1)

In [108]:
M_column

array([[2],
       [7],
       [5]])

In [109]:
M_column.ndim, M_column.shape, M_column.size

(2, (3, 1), 3)

##### 3D

In [110]:
M = np.array([[[1, 2, 100], 
               [3, 4, 100]],
              
              [[5, 6, 100], 
               [7, 8, 100]],
              
              [[9, 10, 100], 
               [11, 12, 100]],
              
              [[13, 14, 100],
               [15, 16, 100]]])
M

array([[[  1,   2, 100],
        [  3,   4, 100]],

       [[  5,   6, 100],
        [  7,   8, 100]],

       [[  9,  10, 100],
        [ 11,  12, 100]],

       [[ 13,  14, 100],
        [ 15,  16, 100]]])

In [111]:
M.ndim, M.shape, M.size

(3, (4, 2, 3), 24)

#### Matrix Operations and Functions

##### Arithmetic Operations

Arithmetic array operators: `+`, `-`, `/`, `*`, and `**` are performed elementwise on NumPy arrays

In [112]:
M = np.array([[3, 4],
              [-1, 5]])
M

array([[ 3,  4],
       [-1,  5]])

In [113]:
M + M

array([[ 6,  8],
       [-2, 10]])

In [114]:
M * M

array([[ 9, 16],
       [ 1, 25]])

In [115]:
M / M

array([[1., 1.],
       [1., 1.]])

In [116]:
M**3

array([[ 27,  64],
       [ -1, 125]])

##### Matrix Multiplication

In [117]:
M @ M

array([[ 5, 32],
       [-8, 21]])

In [118]:
M.dot(M)

array([[ 5, 32],
       [-8, 21]])

###### Example

Compute $2I + 3A - AB$ for

$A = \left[\begin{matrix}1 & 3\\-1 & 7\end{matrix}\right]$

$B = \left[\begin{matrix}5 & 2\\1 & 2\end{matrix}\right]$

In [119]:
A = np.array([[1, 3],
              [-1, 7]])
B = np.array([[5, 2],
              [1, 2]])
I = np.eye(2)

In [120]:
2 * I + 3 * A - A @ B

array([[-3.,  1.],
       [-5., 11.]])

##### Matrix Powers - `np.linalg.matrix_power()`

In [121]:
M

array([[ 3,  4],
       [-1,  5]])

In [122]:
np.linalg.matrix_power(M, 3)

array([[-17, 180],
       [-45,  73]])

In [123]:
M @ M @ M

array([[-17, 180],
       [-45,  73]])

In [124]:
M.dot(M).dot(M)

array([[-17, 180],
       [-45,  73]])

##### Transpose

In [125]:
M

array([[ 3,  4],
       [-1,  5]])

In [126]:
M.T

array([[ 3, -1],
       [ 4,  5]])

Notice that $MM^{T}$ is a symmetric matrix

In [127]:
M @ M.T

array([[25, 17],
       [17, 26]])

In [128]:
M.T @ M

array([[10,  7],
       [ 7, 41]])

##### Inverse

In [129]:
A = np.array([[1, 2],
              [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [130]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

##### Trace

In [131]:
np.trace(A)

5

##### Determinant

In [132]:
# scipy
la.det(A)

-2.0

In [133]:
# numpy 
np.linalg.det(A)

-2.0000000000000004

In [134]:
sp_A = sp.Matrix(A)
sp_A

Matrix([
[1, 2],
[3, 4]])

In [135]:
sp_A.det(), sp.det(sp_A)

(-2, -2)

### Solving Linear Systems

#### Linear Systems

A **linear system of equations** is a collection of linear equations:

$
a_{00}x_{0} + a_{01}x_{1} + \dots + a_{0n}x_{n} = b_{0} \\
a_{10}x_{0} + a_{11}x_{1} + \dots + a_{1n}x_{n} = b_{1} \\
\vdots \\
a_{m0}x_{0} + a_{m1}x_{1} + \dots + a_{mn}x_{n} = b_{m}
$

In matrix notation, a linear system is $Ax = b$ where

$A = 
\left[
\begin{matrix}
a_{00} & a_{01} & \dots & a_{0n} \\
a_{10} & a_{11} & \dots & a \\
\vdots & & & \vdots \\
a_{m0} & a_{m1} & \dots & a_{mn}
\end{matrix}
\right] ,
x = 
\left[
\begin{matrix}
x_{0}  \\
x_{1}  \\
\vdots  \\
x_{n}  
\end{matrix}
\right] ,
b = 
\left[
\begin{matrix}
b_{0}  \\
b_{1}  \\
\vdots  \\
b_{m}  
\end{matrix}
\right]
$

#### Gaussian Elimination

Perform elementary row operations to reduce the system to its row echelen form and then solve

###### Elmentary Row Operations

1. Add $k$ times row $j$ to row $i$
2. Multiply row $i$ by scalar $k$
3. Switch rows $i$ and $j$