<a href="https://colab.research.google.com/github/PaulToronto/Howard-University-Coursera-Linear-Algebra-For-Data-Science-Specialization/blob/main/2_2_1_Introduction_to_Matrix_Algebra_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.2.1 Introduction to Matrix Algebra with Python

## Imports

In [1]:
import sympy as sym
import numpy as np

## 2.2.1.1 Review of Matrix Arithmetic

### Example

Write $2A(\vec{u} + \vec{v})$ as a single matrix.

In [2]:
A = sym.Matrix([[2, 1],
                [0, -4]])
A

Matrix([
[2,  1],
[0, -4]])

In [3]:
u = sym.Matrix([[4],
                [-1]])
u

Matrix([
[ 4],
[-1]])

In [4]:
v = sym.Matrix([[-3],
                [5]])
v

Matrix([
[-3],
[ 5]])

In [5]:
2 * A * (u + v)

Matrix([
[ 12],
[-32]])

### Example

Find and simplify:

1. $B(A^{-1}B)^{-1}$
2. $(A^{T} - B)^{T}$

In [6]:
A = sym.Matrix([[1, 0, 1],
                [0, 3, 0],
                [1, 0, 5]])
A

Matrix([
[1, 0, 1],
[0, 3, 0],
[1, 0, 5]])

In [7]:
B = sym.Matrix([[-1, 0, 1],
                [0, 5, 6],
                [3, 0, 1]])
B

Matrix([
[-1, 0, 1],
[ 0, 5, 6],
[ 3, 0, 1]])

In [8]:
# 1.
B @ (A.inv() @ B).inv()

Matrix([
[1, 0, 1],
[0, 3, 0],
[1, 0, 5]])

In [9]:
# 2.
(A.T - B).T

Matrix([
[2,  0, -2],
[0, -2,  0],
[0, -6,  4]])

Same thing, using `numpy`

In [10]:
Anp = np.array(A, dtype='int')
Anp

array([[1, 0, 1],
       [0, 3, 0],
       [1, 0, 5]])

In [11]:
Bnp = np.array(B, dtype='int')
Bnp

array([[-1,  0,  1],
       [ 0,  5,  6],
       [ 3,  0,  1]])

In [12]:
# 1.
Bnp @ np.linalg.inv(np.linalg.inv(Anp) @ Bnp)

array([[ 1.00000000e+00,  0.00000000e+00,  1.00000000e+00],
       [-8.88178420e-16,  3.00000000e+00, -1.77635684e-15],
       [ 1.00000000e+00,  0.00000000e+00,  5.00000000e+00]])

In [13]:
# 2.
np.transpose(np.transpose(Anp) - Bnp)

array([[ 2,  0, -2],
       [ 0, -2,  0],
       [ 0, -6,  4]])

### Some Matrix Rules

1. $(AB)^{-1} = B^{-1}A^{-1}$
2. $(A^{T})^{T} = A$
3. $(A + B)^{T} = A^{T} + B^{T}$

In light of these rules, lets revisit the previous example. ***We already know that A and B are invertible, which is important.***

Find and simplify:

1. $B(A^{-1}B)^{-1}$
2. $(A^{T} - B)^{T}$

$$
\begin{align}
B(A^{-1}B)^{-1} &= B(B^{-1}A) \\
&= IA \\
&= A
\end{align}
$$

In [14]:
A

Matrix([
[1, 0, 1],
[0, 3, 0],
[1, 0, 5]])

$$
\begin{align}
(A^{T} - B)^{T} &= (A^{T})^{T} - B^{T} \\
&= A - B^{T}
\end{align}
$$

In [15]:
A - B.T

Matrix([
[2,  0, -2],
[0, -2,  0],
[0, -6,  4]])

## 2.2.1.2 Review Matrix Algebra in Python