<a href="https://colab.research.google.com/github/PaulToronto/Howard-University-Coursera-Linear-Algebra-For-Data-Science-Specialization/blob/main/2_2_1_Introduction_to_Matrix_Algebra_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.2.1 Introduction to Matrix Algebra with Python

## Imports

In [1]:
import sympy as sym
import numpy as np
import random

## 2.2.1.1 Review of Matrix Arithmetic

### Example

Write $2A(\vec{u} + \vec{v})$ as a single matrix.

In [2]:
A = sym.Matrix([[2, 1],
                [0, -4]])
A

Matrix([
[2,  1],
[0, -4]])

In [3]:
u = sym.Matrix([[4],
                [-1]])
u

Matrix([
[ 4],
[-1]])

In [4]:
v = sym.Matrix([[-3],
                [5]])
v

Matrix([
[-3],
[ 5]])

In [5]:
2 * A * (u + v)

Matrix([
[ 12],
[-32]])

### Example

Find and simplify:

1. $B(A^{-1}B)^{-1}$
2. $(A^{T} - B)^{T}$

In [6]:
A = sym.Matrix([[1, 0, 1],
                [0, 3, 0],
                [1, 0, 5]])
A

Matrix([
[1, 0, 1],
[0, 3, 0],
[1, 0, 5]])

In [7]:
B = sym.Matrix([[-1, 0, 1],
                [0, 5, 6],
                [3, 0, 1]])
B

Matrix([
[-1, 0, 1],
[ 0, 5, 6],
[ 3, 0, 1]])

In [8]:
# 1.
B @ (A.inv() @ B).inv()

Matrix([
[1, 0, 1],
[0, 3, 0],
[1, 0, 5]])

In [9]:
# 2.
(A.T - B).T

Matrix([
[2,  0, -2],
[0, -2,  0],
[0, -6,  4]])

Same thing, using `numpy`

In [10]:
Anp = np.array(A, dtype='int')
Anp

array([[1, 0, 1],
       [0, 3, 0],
       [1, 0, 5]])

In [11]:
Bnp = np.array(B, dtype='int')
Bnp

array([[-1,  0,  1],
       [ 0,  5,  6],
       [ 3,  0,  1]])

In [12]:
# 1.
Bnp @ np.linalg.inv(np.linalg.inv(Anp) @ Bnp)

array([[ 1.00000000e+00,  0.00000000e+00,  1.00000000e+00],
       [-8.88178420e-16,  3.00000000e+00, -1.77635684e-15],
       [ 1.00000000e+00,  0.00000000e+00,  5.00000000e+00]])

In [13]:
# 2.
np.transpose(np.transpose(Anp) - Bnp)

array([[ 2,  0, -2],
       [ 0, -2,  0],
       [ 0, -6,  4]])

### Some Matrix Rules

1. $(AB)^{-1} = B^{-1}A^{-1}$
2. $(A^{T})^{T} = A$
3. $(A + B)^{T} = A^{T} + B^{T}$

In light of these rules, lets revisit the previous example. ***We already know that A and B are invertible, which is important.***

Find and simplify:

1. $B(A^{-1}B)^{-1}$
2. $(A^{T} - B)^{T}$

$$
\begin{align}
B(A^{-1}B)^{-1} &= B(B^{-1}A) \\
&= IA \\
&= A
\end{align}
$$

In [14]:
A

Matrix([
[1, 0, 1],
[0, 3, 0],
[1, 0, 5]])

$$
\begin{align}
(A^{T} - B)^{T} &= (A^{T})^{T} - B^{T} \\
&= A - B^{T}
\end{align}
$$

In [15]:
A - B.T

Matrix([
[2,  0, -2],
[0, -2,  0],
[0, -6,  4]])

## 2.2.1.2 Review Matrix Algebra in Python

In [16]:
L = sym.Matrix([[-3, 3, 5],
               [2, 5, 1]])
M = sym.Matrix([[3, 1, 2],
                [6, 4, 8],
                [5, 9, 7]])
N = sym.Matrix([[0, -1, 2],
                [2, 6, 1],
                [4, 1, 3]])
P = sym.Matrix([[-3, 3],
                [2, 5],
                [4, 2]])

In [17]:
L

Matrix([
[-3, 3, 5],
[ 2, 5, 1]])

In [18]:
M

Matrix([
[3, 1, 2],
[6, 4, 8],
[5, 9, 7]])

In [19]:
N

Matrix([
[0, -1, 2],
[2,  6, 1],
[4,  1, 3]])

In [20]:
P

Matrix([
[-3, 3],
[ 2, 5],
[ 4, 2]])

### Add Matrices

In [21]:
M + N

Matrix([
[3,  0,  4],
[8, 10,  9],
[9, 10, 10]])

### Subtract Matrices

In [22]:
M - N

Matrix([
[3,  2, 0],
[4, -2, 7],
[1,  8, 4]])

In [23]:
N - M

Matrix([
[-3, -2,  0],
[-4,  2, -7],
[-1, -8, -4]])

### Multiply Matrices

$A \times B$ is only possible if the number of columns of $A$ is equal to the number of rows of $B$

In [24]:
L.shape, P.shape

((2, 3), (3, 2))

In [25]:
L * P

Matrix([
[35, 16],
[ 8, 33]])

In [26]:
L.shape, M.shape

((2, 3), (3, 3))

In [27]:
L * M

Matrix([
[34, 54, 53],
[41, 31, 51]])

In [28]:
M.shape, L.shape # can't multiply these two

((3, 3), (2, 3))

In [29]:
M.shape, N.shape

((3, 3), (3, 3))

In [30]:
M * N

Matrix([
[10,  5, 13],
[40, 26, 40],
[46, 56, 40]])

In [31]:
N * M

Matrix([
[ 4, 14,  6],
[47, 35, 59],
[33, 35, 37]])

## 2.2.1.3 Using Python to Find the Transpose of a Matrix

In [32]:
L = sym.Matrix([[2, 4, 6],
                [8, 10, 12]])
M = sym.Matrix([[3, 1, 2],
                [6, 4, 8],
                [5, 9, 7]])
N = sym.Matrix([[1],
                [2],
                [3]])
P = sym.Matrix([[-3, 3],
                [2, 5],
                [4, 2]])
I = sym.eye(3)

In [33]:
Q = np.array([[0, 3, 1],
              [2, -1, 3],
              [2, 1, 5]])

### Square Matrix

In [34]:
M

Matrix([
[3, 1, 2],
[6, 4, 8],
[5, 9, 7]])

In [35]:
M.transpose()

Matrix([
[3, 6, 5],
[1, 4, 9],
[2, 8, 7]])

In [36]:
M.T

Matrix([
[3, 6, 5],
[1, 4, 9],
[2, 8, 7]])

In [37]:
np.transpose(M)

array([[3, 6, 5],
       [1, 4, 9],
       [2, 8, 7]], dtype=object)

In [38]:
np.transpose(np.array(M, dtype='int'))

array([[3, 6, 5],
       [1, 4, 9],
       [2, 8, 7]])

In [39]:
np.array(M, dtype='int').T

array([[3, 6, 5],
       [1, 4, 9],
       [2, 8, 7]])

### Rectangular Matrix

In [40]:
L

Matrix([
[2,  4,  6],
[8, 10, 12]])

In [41]:
L.T

Matrix([
[2,  8],
[4, 10],
[6, 12]])

In [42]:
np.transpose(L)

array([[2, 8],
       [4, 10],
       [6, 12]], dtype=object)

In [43]:
np.transpose(np.array(L, dtype='int'))

array([[ 2,  8],
       [ 4, 10],
       [ 6, 12]])

### Column Matrix

In [44]:
N

Matrix([
[1],
[2],
[3]])

In [45]:
N.T

Matrix([[1, 2, 3]])

In [46]:
np.transpose(N)

array([[1, 2, 3]], dtype=object)

In [47]:
np.array(N, dtype='int').transpose()

array([[1, 2, 3]])

In [48]:
np.transpose(np.array(N, dtype='int'))

array([[1, 2, 3]])

### Row Matrix

In [49]:
R = Q[1,:]
R

array([ 2, -1,  3])

In [50]:
R.T

array([ 2, -1,  3])

### Identity Matrix

In [51]:
I

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [52]:
I.T

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

## 2.2.1.4 Using Python to Find the Inverse of a Matrix

In [53]:
M = sym.Matrix([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
M

Matrix([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [54]:
M.det() # M is not invertible

0

In [55]:
M[2, 2] = 11
M

Matrix([
[1, 2,  3],
[4, 5,  6],
[7, 8, 11]])

In [56]:
M.det()

-6

In [57]:
M.inv()

Matrix([
[-7/6, -1/3, 1/2],
[ 1/3,  5/3,  -1],
[ 1/2,   -1, 1/2]])

In [58]:
T = sym.Matrix(np.random.randint(-7, 5, size=(6, 6)))
T

Matrix([
[ 2, -1, -6,  4,  3, -5],
[ 0,  1, -2, -7, -3, -2],
[-6,  4, -4,  3, -4, -5],
[ 1, -2, -5, -2,  2, -3],
[-6,  1,  4, -1, -1, -3],
[-5,  0, -5,  2,  2, -6]])

In [59]:
T.det()

7072

In [60]:
if T.det() != 0:
    display(T.inv())
else:
    print('T is not invertible')

Matrix([
[ 363/1768,  191/1768,   -89/1768,   -32/221,    2/221, -43/442],
[ 903/3536, 2455/3536, -1741/3536, -1319/884, -401/884, 415/442],
[   25/221,     5/442,    -11/221,   -31/442,   71/442, -45/442],
[  27/1768, -373/1768,   271/1768,   103/442,   35/442, -50/221],
[ 427/3536, 1435/3536, -1673/3536,  -843/884, -265/884, 347/442],
[-389/1768,  -61/1768,   -41/1768,   -27/442,  -95/442,  41/221]])

### Special Matrices

#### Identity Matrix

In [61]:
I = sym.eye(3, 5)
I.shape # can only find the inverse of a square matrix

(3, 5)

In [62]:
I = sym.eye(3)
I

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [63]:
I.inv()

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

#### Zero Matrix

In [64]:
O = sym.zeros(3)
O

Matrix([
[0, 0, 0],
[0, 0, 0],
[0, 0, 0]])

In [65]:
O.det() # not invertible

0

#### Matrix of all ones

In [66]:
O = sym.ones(4)
O

Matrix([
[1, 1, 1, 1],
[1, 1, 1, 1],
[1, 1, 1, 1],
[1, 1, 1, 1]])

In [67]:
O.det()

0

In [68]:
for i in range(2, 10):
    O = sym.ones(i)
    print(O.det())

0
0
0
0
0
0
0
0


#### Diagonal Matrix

In [69]:
D = sym.diag(1, 2, 3)
D

Matrix([
[1, 0, 0],
[0, 2, 0],
[0, 0, 3]])

In [70]:
D.det()

6

In [71]:
D.inv()

Matrix([
[1,   0,   0],
[0, 1/2,   0],
[0,   0, 1/3]])

## 2.2.1.5 Practice Quiz: Matrix Algebra Functions Using Python

In [72]:
M.inv()

Matrix([
[-7/6, -1/3, 1/2],
[ 1/3,  5/3,  -1],
[ 1/2,   -1, 1/2]])

In [73]:
A = sym.Matrix([[1, -1],
                [2, 2]])
A

Matrix([
[1, -1],
[2,  2]])

In [74]:
B = sym.Matrix([[2, 0],
                [0, -1]])
B

Matrix([
[2,  0],
[0, -1]])

In [75]:
A.inv() * B.inv()

Matrix([
[ 1/4, -1/4],
[-1/4, -1/4]])

In [76]:
(B * A).inv()

Matrix([
[ 1/4, -1/4],
[-1/4, -1/4]])

## 2.2.1.6 Using Matrix Algebra in Python

- This section focuses on using `numpy` rather than `sympy`

In [77]:
L = np.linspace(-8, 8, 9)
L

array([-8., -6., -4., -2.,  0.,  2.,  4.,  6.,  8.])

In [78]:
M = L.reshape(3, 3)
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [79]:
N = np.random.randint(-8, 8, size=(3, 3))
N

array([[ 6,  2,  1],
       [ 7,  7, -7],
       [-1,  6, -3]])

In [80]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
B = np.array([[7, 2, -3],
              [0, 1, 6]])
B

array([[ 7,  2, -3],
       [ 0,  1,  6]])

### Multiply Matrices

In [82]:
np.matmul(M, N)

array([[-86., -82.,  46.],
       [-14.,   8.,  -8.],
       [ 58.,  98., -62.]])

In [83]:
M.dot(N)

array([[-86., -82.,  46.],
       [-14.,   8.,  -8.],
       [ 58.,  98., -62.]])

In [84]:
np.dot(M, N)

array([[-86., -82.,  46.],
       [-14.,   8.,  -8.],
       [ 58.,  98., -62.]])

In [85]:
M @ N

array([[-86., -82.,  46.],
       [-14.,   8.,  -8.],
       [ 58.,  98., -62.]])

In [86]:
# careful, does not work
# this does element-wise multiplication
M * N

array([[-48., -12.,  -4.],
       [-14.,   0., -14.],
       [ -4.,  36., -24.]])

In [87]:
A.shape, B.shape
# A @ B is not possible
# B @ A is also not possible

((2, 3), (2, 3))

In [88]:
A.shape, B.T.shape

((2, 3), (3, 2))

In [89]:
A @ B.T

array([[ 2, 20],
       [20, 41]])

### Determinant

- A matrix with a determinant of 0, is called a **singular matrix**
- Singular matrices are not invertible

In [90]:
np.linalg.det(M)

0.0

In [91]:
np.linalg.det(N)

230.99999999999994

### Inverse

In [92]:
if np.linalg.det(N) != 0:
    print(np.linalg.inv(N))
else:
    print('`N` is not invertible')

[[ 0.09090909  0.05194805 -0.09090909]
 [ 0.12121212 -0.07359307  0.21212121]
 [ 0.21212121 -0.16450216  0.12121212]]


### Matrix Addition and Subtraction

In [93]:
M.shape, N.shape

((3, 3), (3, 3))

In [94]:
M + N

array([[-2., -4., -3.],
       [ 5.,  7., -5.],
       [ 3., 12.,  5.]])

In [95]:
M - N

array([[-14.,  -8.,  -5.],
       [ -9.,  -7.,   9.],
       [  5.,   0.,  11.]])

In [96]:
N - M

array([[ 14.,   8.,   5.],
       [  9.,   7.,  -9.],
       [ -5.,   0., -11.]])

In [97]:
2 * M

array([[-16., -12.,  -8.],
       [ -4.,   0.,   4.],
       [  8.,  12.,  16.]])

## 2.2.1.7 Quiz