<a href="https://colab.research.google.com/github/PaulToronto/Howard-University-Coursera-Linear-Algebra-For-Data-Science-Specialization/blob/main/3_1_2_Solving_Systems_of_Linear_Equations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3.1.2 Solving Systems of Linear Equations

## Imports

In [12]:
import numpy as np
import sympy as sym
import random

## 3.1.2.1 Solvng Systems Using the Inverse

### What is need to use the inverse of the coefficient matrix to solve a system:

1. The number of equations and the number of variables must be the same
2. The coefficient matrix must be invertible

### Discussion

Consider the following system with 3 variables and 3 equations.

$$
\begin{align}
a_1x + a_2y + a_3z &= d_1 \\
b_1x + b_2y + b_3z &= d_2 \\
c_1x + c_2y + c_3z &= d_3
\end{align}
$$

Let A denote the coefficent matrix.

In [2]:
a1, a2, a3, b1, b2, b3, c1, c2, c3 = sym.symbols('a_1 a_2 a_3 b_1 b_2 b_3 c_1 c_2 c_3')

A = sym.Matrix([[a1, a2, a3],
                [b1, b2, b3],
                [c1, c2, c3]])
A

Matrix([
[a_1, a_2, a_3],
[b_1, b_2, b_3],
[c_1, c_2, c_3]])

In [3]:
x, y, z, = sym.symbols('x y z')
X = sym.Matrix([[x],
                [y],
                [z]])
X

Matrix([
[x],
[y],
[z]])

In [4]:
d1, d2, d3 = sym.symbols('d_1 d_2 d_3')
C = sym.Matrix([[d1],
                [d2],
                [d3]])
C

Matrix([
[d_1],
[d_2],
[d_3]])

In [5]:
A @ X

Matrix([
[a_1*x + a_2*y + a_3*z],
[b_1*x + b_2*y + b_3*z],
[c_1*x + c_2*y + c_3*z]])

Another way of writing the linear system:

$$
A \cdot X = C
$$

If $A$ is invertible, then:

$$
\begin{align}
A^{-1}AX &= A^{-1}C \\
IX &= A^{-1}C \\
X &= A^{-1}C
\end{align}
$$

In [6]:
A.inv() @ C

Matrix([
[ d_1*(b_2*c_3 - b_3*c_2)/(a_1*b_2*c_3 - a_1*b_3*c_2 - a_2*b_1*c_3 + a_2*b_3*c_1 + a_3*b_1*c_2 - a_3*b_2*c_1) + d_2*(-a_2*c_3 + a_3*c_2)/(a_1*b_2*c_3 - a_1*b_3*c_2 - a_2*b_1*c_3 + a_2*b_3*c_1 + a_3*b_1*c_2 - a_3*b_2*c_1) + d_3*(a_2*b_3 - a_3*b_2)/(a_1*b_2*c_3 - a_1*b_3*c_2 - a_2*b_1*c_3 + a_2*b_3*c_1 + a_3*b_1*c_2 - a_3*b_2*c_1)],
[d_1*(-b_1*c_3 + b_3*c_1)/(a_1*b_2*c_3 - a_1*b_3*c_2 - a_2*b_1*c_3 + a_2*b_3*c_1 + a_3*b_1*c_2 - a_3*b_2*c_1) + d_2*(a_1*c_3 - a_3*c_1)/(a_1*b_2*c_3 - a_1*b_3*c_2 - a_2*b_1*c_3 + a_2*b_3*c_1 + a_3*b_1*c_2 - a_3*b_2*c_1) + d_3*(-a_1*b_3 + a_3*b_1)/(a_1*b_2*c_3 - a_1*b_3*c_2 - a_2*b_1*c_3 + a_2*b_3*c_1 + a_3*b_1*c_2 - a_3*b_2*c_1)],
[ d_1*(b_1*c_2 - b_2*c_1)/(a_1*b_2*c_3 - a_1*b_3*c_2 - a_2*b_1*c_3 + a_2*b_3*c_1 + a_3*b_1*c_2 - a_3*b_2*c_1) + d_2*(-a_1*c_2 + a_2*c_1)/(a_1*b_2*c_3 - a_1*b_3*c_2 - a_2*b_1*c_3 + a_2*b_3*c_1 + a_3*b_1*c_2 - a_3*b_2*c_1) + d_3*(a_1*b_2 - a_2*b_1)/(a_1*b_2*c_3 - a_1*b_3*c_2 - a_2*b_1*c_3 + a_2*b_3*c_1 + a_3*b_1*c_2 - a_3*b_2

### Example

$$
\begin{align}
x + 2y + 3z &= 9 \\
4x + 5y + 6z &= 24 \\
3x + y - 2z &= 4
\end{align}
$$

In [7]:
A = sym.Matrix([[1, 2, 3],
                [4, 5, 6],
                [3, 1, -2]])
A

Matrix([
[1, 2,  3],
[4, 5,  6],
[3, 1, -2]])

In [8]:
C = sym.Matrix([9, 24, 4])
C

Matrix([
[ 9],
[24],
[ 4]])

In [9]:
# check to makes sure A is invertible
A.det()

3

In [10]:
X = A.inv() @ C
x = X[0]; y = X[1]; z = X[2]
x, y, z

(4, -2, 3)

In [11]:
# verify answer:
A * sym.Matrix([4, -2, 3])

Matrix([
[ 9],
[24],
[ 4]])

## 3.1.2.2 Cramer's Rule

Consider the system:

$$
\begin{align}
ax + by &= u \\
cx + by &= v
\end{align}
$$

Alternately,

$$
A \cdot X = C
$$



In [13]:
a, b, c, d, x, y, u, v = sym.symbols('a b c d x y u v')
A = sym.Matrix([[a, b],
                [c, d]])
A

Matrix([
[a, b],
[c, d]])

In [14]:
X = sym.Matrix([x, y])
X

Matrix([
[x],
[y]])

In [15]:
C = sym.Matrix([u, v])
C

Matrix([
[u],
[v]])

### Cramer's Rule

$$
x = \frac{D_x}{\det{(A)}}, y = \frac{D_y}{\det{(A)}}
$$

In [22]:
# - replace the coefficients of `x` with `u` and `v`
# - then find the determinant
Dx = sym.Matrix([[u, b],
                 [v, d]]).det()
Dx

-b*v + d*u

In [23]:
Dy = sym.Matrix([[a, u],
                 [c, v]]).det()
Dy

a*v - c*u

In [24]:
x = Dx / A.det()
x

(-b*v + d*u)/(a*d - b*c)

In [25]:
y = Dy / A.det()
y

(a*v - c*u)/(a*d - b*c)

In [33]:
# using inverse method to verify
X = A.inv() @ C
X

Matrix([
[-b*v/(a*d - b*c) + d*u/(a*d - b*c)],
[ a*v/(a*d - b*c) - c*u/(a*d - b*c)]])

#### Example

In [34]:
A = sym.Matrix([[1, 2],
                [3, 4]])
A

Matrix([
[1, 2],
[3, 4]])

In [36]:
C = sym.Matrix([1, 3])
C

Matrix([
[1],
[3]])

In [45]:
Dx = A.copy()
Dx[:,0] = C
Dx = Dx.det()
x = Dx / A.det()
x

1

In [48]:
Dy = A.copy()
Dy[:, 1] = C
Dy = Dy.det()
y = Dy / A.det()
y

0

In [50]:
# verify using inverse method
A.inv() @ C

Matrix([
[1],
[0]])

### Cramer's Rule with $3 \times 3$ Matrix

Consider the system:

$$
\begin{align}
x + 2y + 3z &= 9 \\
4x + 5y + 6z &= 24 \\
3x + y - 2z &= 4
\end{align}
$$

In [52]:
A = sym.Matrix([[1, 2, 3],
                [4, 5, 6],
                [3, 1, -2]])
C = sym.Matrix([9, 24, 4])
C

Matrix([
[ 9],
[24],
[ 4]])

In [55]:
D1 = A.copy()
D1[:, 0] = C
D1 = D1.det()

D2 = A.copy()
D2[:, 1] = C
D2 = D2.det()

D3 = A.copy()
D3[:, 2] = C
D3 = D3.det()

In [56]:
detA = A.det()
detA

3

In [58]:
x, y, z = D1/detA, D2/detA, D3/detA
x, y, z

(4, -2, 3)

In [61]:
# verify using inverse
A.inv() * C

Matrix([
[ 4],
[-2],
[ 3]])

## 3.1.2.3 Practice Quiz

In [63]:
M = np.array([[2, 1], [1, -1]])
M

array([[ 2,  1],
       [ 1, -1]])

In [64]:
b = np.array([[5], [1]])
b

array([[5],
       [1]])

$$
M \cdot X = b
$$

In [65]:
np.linalg.inv(M).dot(b)

array([[2.],
       [1.]])

In [66]:
M = np.array([[2, 4, 6],
              [4, 5, 6],
              [1, 2, 3]])
b = np.array([[1], [-2], [2]])

In [67]:
M, b

(array([[2, 4, 6],
        [4, 5, 6],
        [1, 2, 3]]),
 array([[ 1],
        [-2],
        [ 2]]))

In [70]:
np.linalg.det(M)

0.0

## 3.1.2.4 Quiz

In [78]:
A = sym.Matrix([[4, 1, -2],
                [2, -3, 3],
                [-6, -2, 1]])
A

Matrix([
[ 4,  1, -2],
[ 2, -3,  3],
[-6, -2,  1]])

In [79]:
A.inv()

Matrix([
[  1/12, 1/12, -1/12],
[  -5/9, -2/9,  -4/9],
[-11/18, 1/18, -7/18]])

In [80]:
sym.Rational(1, 36) * sym.Matrix([[3, 3, -3],
                                  [-20, -8, -16],
                                  [-22, 2, -14]])

Matrix([
[  1/12, 1/12, -1/12],
[  -5/9, -2/9,  -4/9],
[-11/18, 1/18, -7/18]])

In [82]:
A = sym.Matrix([[4, 1, -2],
                [2, -3, 3],
                [-6, -2, 1]])
A

Matrix([
[ 4,  1, -2],
[ 2, -3,  3],
[-6, -2,  1]])

In [83]:
b = sym.Matrix([0, 9, 0])
b

Matrix([
[0],
[9],
[0]])

$$A \cdot X = B$$

In [85]:
X = A.inv() @ b
X

Matrix([
[3/4],
[ -2],
[1/2]])

In [86]:
A = sym.Matrix([[2, -1, 0, 0],
                [0, 1, 1, 1],
                [0, 0, 1, 2]])
A

Matrix([
[2, -1, 0, 0],
[0,  1, 1, 1],
[0,  0, 1, 2]])

In [89]:
A.rref(pivots=False)

Matrix([
[1, 0, 0, -1/2],
[0, 1, 0,   -1],
[0, 0, 1,    2]])

In [97]:
M = sym.Matrix([[4, 2, 5],
                [2, 1, 8]])
M

Matrix([
[4, 2, 5],
[2, 1, 8]])

In [99]:
M.rref(pivots=False)

Matrix([
[1, 1/2, 0],
[0,   0, 1]])